codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 1%
        paths:
          - "weave/"
    patch:
      default:
        target: auto
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "tests/"
  - "docs/"
  - "examples/"
  - "scripts/"
  - "weave_query/tests/"
  - "sdks/node/"
  - "**/*_test.py"
  - "**/*_tests.py"
  - "**/test_*.py"
  - "**/tests_*.py"
  - "**/__pycache__"
  - "**/*.pyc"