# Should match version in integration_test/package.json
FROM cypress/included:10.11.0 as builder

RUN apt update
RUN apt -y install python3-venv gcc python3-dev g++
COPY requirements.txt requirements.test.txt /root/
WORKDIR /root
RUN python3 -m venv venv
RUN /bin/bash -c "source venv/bin/activate && pip install -r requirements.test.txt"
COPY requirements.dev.txt /root/
RUN /bin/bash -c "source venv/bin/activate && pip install -r requirements.dev.txt"

COPY integration_test/package.json /root/integration_test/package.json
COPY integration_test/package-lock.json /root/integration_test/package-lock.json
RUN cd integration_test && npm install

# final stage
FROM cypress/included:10.11.0

WORKDIR /root
COPY --from=builder /root/venv venv
COPY --from=builder /root/integration_test integration_test
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
ENTRYPOINT "/bin/bash"
