import json
from typing import Annotated, Any, ClassVar, Literal

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field, model_validator

from weave.shared import serialization_metadata
from weave.shared.interface.builtin_object_classes import base_object_def
from weave.shared.refs import ObjectRef

ResponseFormat = Literal["json_object", "json_schema", "text"]


def is_response_format(value: Any) -> bool:
    return isinstance(value, str) and value in {"json_object", "text"}


class Message(BaseModel):
    """A message in a conversation with an LLM.

    Attributes:
        role: The role of the message's author. Can be: system, user, assistant, function or tool.
        content: The contents of the message. Required for all messages, but may be null for assistant messages with function calls.
        name: The name of the author of the message. Required if role is "function". Must match the name of the function represented in content.
              Can contain characters (a-z, A-Z, 0-9), and underscores, with a maximum length of 64 characters.
        function_call: The name and arguments of a function that should be called, as generated by the model.
        tool_call_id: Tool call that this message is responding to.
    """

    role: str
    content: str | list[dict] | None = None
    name: str | None = None
    function_call: dict | None = None
    tool_call_id: str | None = None


class LLMStructuredCompletionModelDefaultParams(BaseModel):
    """Default parameters for LLMStructuredCompletionModel.

    Attributes:
        messages_template: A list of Messages to use as a template. Messages can contain
            template variables using {variable_name} syntax. These will be substituted
            when predict() is called with template_vars.
        prompt: A reference string to a MessagesPrompt object. If provided, this takes
            precedence over messages_template. The referenced prompt's format() method will
            be used to generate messages with template variable substitution.
            Example: "weave:///entity/project/object/my_prompt:latest"
    """

    # This is a list of Messages, loosely following litellm's message format
    # https://docs.litellm.ai/docs/completion/input#properties-of-messages
    messages_template: list[Message] | None = None
    prompt: base_object_def.RefStr | None = None

    temperature: float | None = None
    top_p: float | None = None
    max_tokens: int | None = None
    presence_penalty: float | None = None
    frequency_penalty: float | None = None
    stop: list[str] | None = None
    n_times: int | None = None
    functions: list[dict] | None = None

    # Either json, text, or json_schema
    response_format: ResponseFormat | None = None

    # TODO: Currently not used. Fast follow up with json_schema
    # if default_params.response_format is set to JSON_SCHEMA, this will be used
    # response_format_schema: dict | None = None


def cast_to_message_list(obj: Any) -> list[Message]:
    if isinstance(obj, Message):
        return [obj]
    elif isinstance(obj, dict):
        return [Message.model_validate(obj)]
    elif isinstance(obj, str):
        return [Message(content=obj, role="user")]
    elif isinstance(obj, list):
        return [cast_to_message(item) for item in obj]
    raise TypeError("Unable to cast to Message")


def cast_to_message(obj: Any) -> Message:
    if isinstance(obj, Message):
        return obj
    elif isinstance(obj, dict):
        return Message.model_validate(obj)
    elif isinstance(obj, str):
        return Message(content=obj, role="user")
    raise TypeError("Unable to cast to Message")


def cast_to_llm_structured_model_params(
    obj: Any,
) -> LLMStructuredCompletionModelDefaultParams:
    if isinstance(obj, LLMStructuredCompletionModelDefaultParams):
        return obj
    elif isinstance(obj, dict):
        return LLMStructuredCompletionModelDefaultParams.model_validate(obj)

    raise TypeError("Unable to cast to LLMStructuredCompletionModelDefaultParams")


MessageListLike = Annotated[list[Message], BeforeValidator(cast_to_message_list)]
MessageLike = Annotated[Message, BeforeValidator(cast_to_message)]
LLMStructuredModelParamsLike = Annotated[
    LLMStructuredCompletionModelDefaultParams,
    BeforeValidator(cast_to_llm_structured_model_params),
]


class LLMStructuredCompletionModel(base_object_def.BaseObject):
    model_config = ConfigDict(arbitrary_types_allowed=True, extra="forbid")

    # Stored as the SDK model in weave.flow, so the server writes the same _bases
    # and digest for it.
    _weave_serialized_bases: ClassVar[tuple[str, ...]] = (
        "Model",
        "Object",
        "BaseModel",
    )

    ref: ObjectRef | None = None

    # <provider>/<model> or ref to a provider model
    llm_model_id: str | base_object_def.RefStr

    default_params: LLMStructuredModelParamsLike = Field(
        default_factory=LLMStructuredCompletionModelDefaultParams
    )

    @model_validator(mode="before")
    @classmethod
    def strip_weave_serialization_metadata(cls, data: Any) -> Any:
        return serialization_metadata.strip_weave_serialization_metadata(data)


def parse_response(
    response_payload: dict, response_format: ResponseFormat | None
) -> Message | str | dict[str, Any]:
    """Extract the model output from an LLM completion response payload.

    Raises:
        RuntimeError: the provider returned a top-level `error` field.
        ValueError: the payload is malformed (missing choices/message), the
            content is None/empty, or json_object parsing failed.
    """
    if response_payload.get("error"):
        raise RuntimeError(f"LLM API returned an error: {response_payload['error']}")

    choices = response_payload.get("choices")
    if not choices:
        raise ValueError(
            "LLM response is missing 'choices' -> the upstream call likely failed "
            "(invalid API key, content filtering, or provider error). "
            f"Response keys: {sorted(response_payload.keys())}"
        )

    message = choices[0].get("message") if isinstance(choices[0], dict) else None
    if not isinstance(message, dict):
        raise TypeError(
            f"LLM response choice did not contain a message dict: {choices[0]!r}"
        )
    content = message.get("content")

    if response_format == "text":
        if content is None:
            raise ValueError(
                "LLM response content is None -> the model returned no text. "
                "Check your API key, model config, and content filtering settings."
            )
        return content
    elif response_format == "json_object":
        if content is None or (isinstance(content, str) and not content.strip()):
            raise ValueError(
                "LLM response content was empty when JSON output was requested. "
                "Check your API key and that the model supports JSON mode."
            )
        try:
            return json.loads(content)
        except json.JSONDecodeError as e:
            snippet = content if len(content) <= 200 else content[:200] + "..."
            raise ValueError(
                f"LLM response was not valid JSON (response_format=json_object). "
                f"Content snippet: {snippet!r}"
            ) from e
    else:
        raise ValueError(f"Invalid response_format: {response_format}")


def _prepare_llm_messages(
    template_messages: list[Message] | None,
    user_input: list[Message],
) -> list[dict[str, Any]]:
    """Prepares a list of message dictionaries for the LLM API from a message template and user input.
    Helper function for PlaygroundModel.predict.
    Returns a list of message dictionaries.
    """
    final_messages_dicts: list[dict[str, Any]] = []

    # 1. Initialize messages from template
    if template_messages:
        for msg_template in template_messages:
            msg_dict = msg_template.model_dump(exclude_none=True)
            final_messages_dicts.append(msg_dict)

    # 2. Append user_input messages
    for u_msg in user_input:
        final_messages_dicts.append(u_msg.model_dump(exclude_none=True))

    return final_messages_dicts


def parse_params_to_litellm_params(
    params_source: LLMStructuredCompletionModelDefaultParams,
) -> dict[str, Any]:
    final_params: dict[str, Any] = {}
    source_dict_to_iterate: dict[str, Any] = params_source.model_dump(exclude_none=True)

    for key, value in source_dict_to_iterate.items():
        if key == "response_format":
            litellm_response_format_value = None
            if isinstance(value, str) and is_response_format(value):
                litellm_response_format_value = {"type": value}
            elif (
                isinstance(value, dict)
                and "type" in value
                and is_response_format(value["type"])
            ):  # Pre-formed dict with valid type
                litellm_response_format_value = value

            if litellm_response_format_value is not None:
                final_params["response_format"] = litellm_response_format_value
        elif key == "n_times":
            final_params["n"] = value
        elif key == "messages_template":
            pass
        elif key in {"functions", "stop"}:
            if isinstance(value, list) and len(value) > 0:
                final_params[key] = value
        else:
            final_params[key] = value

    return final_params
