from weave.integrations.patch import *

__all__ = [
    "patch_anthropic",
    "patch_autogen",
    "patch_cerebras",
    "patch_cohere",
    "patch_crewai",
    "patch_dspy",
    "patch_google_genai",
    "patch_groq",
    "patch_huggingface",
    "patch_instructor",
    "patch_langchain",
    "patch_litellm",
    "patch_llamaindex",
    "patch_mcp",
    "patch_mistral",
    "patch_notdiamond",
    "patch_nvidia",
    "patch_openai",
    "patch_openai_agents",
    "patch_openai_realtime",
    "patch_smolagents",
    "patch_verdict",
    "patch_verifiers",
    "patch_vertexai",
]
