#!/usr/bin/env node

// Build-time tool, not part of the published package. It is invoked by npm
// scripts (`prebuild` / `pretest`) and runs directly on Node — it is never
// compiled, bundled, or imported by consumer code. The `.mjs` extension forces
// Node to treat this file as an ES module regardless of the package's `"type"`
// field (which is currently `"commonjs"`), so `import` / `import.meta` are
// available here. Files under `src/` cannot use either CJS or ESM globals
// directly because they must compile cleanly to both formats.

import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));

const pkgPath = join(scriptDir, '..', 'package.json');
const outPath = join(scriptDir, '..', 'src', 'utils', 'generatedVersion.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = pkg.version;

if (typeof version !== 'string' || version.length === 0) {
  console.error('generate-version: package.json is missing a version field');
  process.exit(1);
}

const contents =
  `// This file is auto-generated by scripts/generate-version.mjs. Do not edit.\n` +
  `export const packageVersion = ${JSON.stringify(version)};\n`;

mkdirSync(dirname(outPath), {recursive: true});
writeFileSync(outPath, contents);
