"""Compatibility exports for weave.shared.refs_conversion."""

from weave.shared.refs_conversion import (
    A,
    Any,
    B,
    BaseModel,
    C,
    Callable,
    E,
    InvalidExternalRef,
    InvalidInternalRef,
    NamedTuple,
    RequestTooLarge,
    TypeVar,
    cast,
    dataclasses,
    json,
    logger,
    logging,
    replace_external_weave_ref,
    ri,
    universal_ext_to_int_ref_converter,
    universal_int_to_ext_ref_converter,
    weave_internal_prefix,
    weave_prefix,
)

__all__ = [
    "A",
    "Any",
    "B",
    "BaseModel",
    "C",
    "Callable",
    "E",
    "InvalidExternalRef",
    "InvalidInternalRef",
    "NamedTuple",
    "RequestTooLarge",
    "TypeVar",
    "cast",
    "dataclasses",
    "json",
    "logger",
    "logging",
    "replace_external_weave_ref",
    "ri",
    "universal_ext_to_int_ref_converter",
    "universal_int_to_ext_ref_converter",
    "weave_internal_prefix",
    "weave_prefix",
]
