import {instrumentOpenAI} from '../integrations/openai.js';
import {instrumentAnthropic} from './anthropic.js';
import {instrumentGoogleGenAI} from './googleGenAI.js';
import {instrumentOpenAIAgent} from './openai.agent.js';
import {instrumentOpenAIRealtimeAgent} from './openai.realtime.agent.js';
instrumentOpenAI();
instrumentAnthropic();
instrumentGoogleGenAI();
instrumentOpenAIAgent();
instrumentOpenAIRealtimeAgent();
