import {instrumentOpenAI} from '../integrations/openai';
import {instrumentAnthropic} from './anthropic';
import {instrumentClaudeAgentSdk} from './claudeAgentSdk';
import {instrumentGoogleADK} from './googleAdk';
import {instrumentGoogleGenAI} from './googleGenAI';
import {instrumentOpenAIAgent} from './openai.agent';
import {instrumentOpenAIRealtimeAgent} from './openai.realtime.agent';
instrumentOpenAI();
instrumentAnthropic();
instrumentClaudeAgentSdk();
instrumentGoogleADK();
instrumentGoogleGenAI();
instrumentOpenAIAgent();
instrumentOpenAIRealtimeAgent();
