"""SQL assertion tests for GenAI query layer.

Each test verifies the SQL structure and parameter values produced by a query
handler method. Uses sqlparse to normalize whitespace. Parameter names are
auto-generated by ParamBuilder so we verify values rather than names.
"""

import copy
import re
from typing import Any
from unittest.mock import MagicMock

import pytest
import sqlparse

from weave.trace_server.agent_clickhouse import (
    _SPANS_LIST_COLS,
    AgentQueryHandler,
)
from weave.trace_server.agent_types import (
    AgentConversationsQueryFilters,
    AgentConversationsQueryReq,
    AgentCustomAttrFilter,
    AgentSearchReq,
    AgentSortBy,
    AgentSpansQueryFilters,
    AgentSpansQueryReq,
    AgentSpansTraceReq,
    AgentsQueryFilters,
    AgentsQueryReq,
    AgentTracesQueryReq,
    AgentVersionsQueryReq,
)
from weave.trace_server.query_builder.agent_query_builder import (
    SPAN_SORTABLE_COLS,
    build_order_by,
)

# ---------------------------------------------------------------------------
# Test infrastructure
# ---------------------------------------------------------------------------


def _fmt(sql: str) -> str:
    """Normalize SQL whitespace via sqlparse."""
    return sqlparse.format(sql, reindent=True).strip()


def _strip_param_names(sql: str) -> str:
    """Replace {genai_N:Type} with {_:Type} so we can compare SQL structure
    without depending on ParamBuilder's auto-generated names.
    """
    return re.sub(r"\{[^}:]+:([^}]+)\}", r"{_:\1}", sql)


def _assert_sql_structure(expected: str, actual: str) -> None:
    """Assert SQL matches structurally (ignoring auto-generated param names)."""
    exp = _strip_param_names(_fmt(expected))
    act = _strip_param_names(_fmt(actual))
    assert exp == act, f"\nExpected:\n{exp}\n\nGot:\n{act}"


def _assert_param_values(expected_values: set, actual_params: dict) -> None:
    """Assert all expected values appear in the params dict."""
    actual_values = set(actual_params.values())
    missing = expected_values - actual_values
    assert not missing, f"Missing param values: {missing}\nGot: {actual_params}"


class _QueryCapture:
    """Mock query_fn that records every call and returns an empty result."""

    def __init__(self) -> None:
        self.calls: list[tuple[str, dict[str, Any]]] = []

    def __call__(self, sql: str, parameters: dict[str, Any]) -> Any:
        self.calls.append((sql, copy.deepcopy(parameters)))
        result = MagicMock()
        result.result_rows = []
        result.column_names = []
        return result


@pytest.fixture
def ch() -> _QueryCapture:
    return _QueryCapture()


@pytest.fixture
def handler(ch: _QueryCapture) -> AgentQueryHandler:
    return AgentQueryHandler(ch)


# ============================================================================
# spans_query
# ============================================================================


class TestSpansQuery:
    def test_basic(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.spans_query(AgentSpansQueryReq(project_id="p1"))

        assert len(ch.calls) == 2

        _assert_sql_structure(
            "SELECT count() FROM spans s WHERE s.project_id = {p:String}",
            ch.calls[0][0],
        )
        _assert_param_values({"p1"}, ch.calls[0][1])

        _assert_sql_structure(
            f"""
            SELECT {_SPANS_LIST_COLS}
            FROM spans s
            WHERE s.project_id = {{p:String}}
            ORDER BY started_at DESC
            LIMIT {{l:UInt64}} OFFSET {{o:UInt64}}
            """,
            ch.calls[1][0],
        )
        _assert_param_values({"p1", 100, 0}, ch.calls[1][1])

    def test_with_filters_time_sort(
        self, handler: AgentQueryHandler, ch: _QueryCapture
    ) -> None:
        handler.spans_query(
            AgentSpansQueryReq(
                project_id="p1",
                filters=AgentSpansQueryFilters(
                    agent_name="bot",
                    custom_filters=[
                        AgentCustomAttrFilter(
                            attr_key="env", operator="eq", value="prod"
                        )
                    ],
                ),
                start="2026-01-01",
                end="2026-02-01",
                sort_by=[AgentSortBy(field="input_tokens", direction="asc")],
            )
        )

        sql = ch.calls[1][0]
        assert "ORDER BY input_tokens asc" in sql
        _assert_param_values(
            {"p1", "2026-01-01", "2026-02-01", "bot", "env", "prod", 100, 0},
            ch.calls[1][1],
        )

    def test_limit_capped(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.spans_query(AgentSpansQueryReq(project_id="p1", limit=99999))
        assert 10000 in ch.calls[1][1].values()


# ============================================================================
# spans_trace
# ============================================================================


class TestSpansTrace:
    def test_basic(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.spans_trace(AgentSpansTraceReq(project_id="p1", trace_id="t1"))

        assert len(ch.calls) == 1
        sql = ch.calls[0][0]
        assert "FROM spans s" in sql
        assert "ORDER BY s.started_at ASC" in sql
        assert "input_messages" in sql
        assert "raw_span_dump" not in sql
        _assert_param_values({"p1", "t1"}, ch.calls[0][1])


# ============================================================================
# traces_query
# ============================================================================


class TestTracesQuery:
    def test_basic(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.traces_query(AgentTracesQueryReq(project_id="p1"))

        assert len(ch.calls) == 2

        _assert_sql_structure(
            """
            SELECT count() FROM (
                SELECT trace_id FROM spans
                WHERE project_id = {p:String}
                GROUP BY trace_id
            )
            """,
            ch.calls[0][0],
        )

        sql = ch.calls[1][0]
        assert "GROUP BY trace_id" in sql
        assert "ORDER BY last_seen DESC, trace_id" in sql
        assert "groupUniqArray(agent_name)" in sql
        _assert_param_values({"p1", 100, 0}, ch.calls[1][1])

    def test_with_filters(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.traces_query(
            AgentTracesQueryReq(
                project_id="p1",
                conversation_id="conv-1",
                agent_name="bot",
                start="2026-01-01",
                end="2026-02-01",
            )
        )
        _assert_param_values(
            {"p1", "conv-1", "bot", "2026-01-01", "2026-02-01", 100, 0},
            ch.calls[1][1],
        )


# ============================================================================
# agents_query
# ============================================================================


class TestAgentsQuery:
    def test_basic(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.agents_query(AgentsQueryReq(project_id="p1"))

        assert len(ch.calls) == 2
        sql = ch.calls[0][0]
        assert "FROM agents" in sql
        assert "GROUP BY agent_name" in sql
        assert "ORDER BY last_seen DESC, agent_name" in sql
        _assert_param_values({"p1"}, ch.calls[0][1])

    def test_with_filter(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.agents_query(
            AgentsQueryReq(
                project_id="p1", filters=AgentsQueryFilters(agent_name="my-agent")
            )
        )
        _assert_param_values({"p1", "my-agent"}, ch.calls[0][1])


# ============================================================================
# agent_versions_query
# ============================================================================


class TestAgentVersionsQuery:
    def test_basic(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.agent_versions_query(
            AgentVersionsQueryReq(project_id="p1", agent_name="a1")
        )

        assert len(ch.calls) == 2
        sql = ch.calls[0][0]
        assert "FROM agent_versions" in sql
        assert "GROUP BY agent_version" in sql
        assert "ORDER BY last_seen DESC" in sql
        _assert_param_values({"p1", "a1"}, ch.calls[0][1])


# ============================================================================
# conversations_query
# ============================================================================


class TestConversationsQuery:
    def test_basic(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.conversations_query(AgentConversationsQueryReq(project_id="p1"))

        assert len(ch.calls) == 2

        count_sql = ch.calls[0][0]
        assert "conversation_id != ''" in count_sql
        assert "GROUP BY conversation_id" in count_sql

        data_sql = ch.calls[1][0]
        assert "countIf(operation_name = 'invoke_agent') AS turn_count" in data_sql
        assert "groupUniqArray(agent_name)" in data_sql
        assert "ORDER BY last_seen DESC, conversation_id" in data_sql
        _assert_param_values({"p1"}, ch.calls[0][1])

    def test_with_filter_and_array_sort(
        self, handler: AgentQueryHandler, ch: _QueryCapture
    ) -> None:
        handler.conversations_query(
            AgentConversationsQueryReq(
                project_id="p1",
                filters=AgentConversationsQueryFilters(agent_name="bot"),
                sort_by=[AgentSortBy(field="agent_name", direction="asc")],
            )
        )
        assert "ORDER BY arrayElement(agent_names, 1) asc" in ch.calls[1][0]
        _assert_param_values({"p1", "bot"}, ch.calls[1][1])


# ============================================================================
# search
# ============================================================================


class TestSearch:
    def test_basic(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.search(AgentSearchReq(project_id="p1", query="hello"))

        assert len(ch.calls) == 1
        sql = ch.calls[0][0]
        assert "FROM message_search FINAL" in sql
        assert "ORDER BY started_at DESC" in sql
        _assert_param_values({"p1", "%hello%", 20, 0}, ch.calls[0][1])

    def test_with_filters(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.search(
            AgentSearchReq(
                project_id="p1",
                query="test",
                agent_name="bot",
                roles=["user", "assistant"],
            )
        )
        params = ch.calls[0][1]
        assert "p1" in params.values()
        assert "%test%" in params.values()
        assert "bot" in params.values()
        assert ["user", "assistant"] in params.values()

    def test_limit_capped(self, handler: AgentQueryHandler, ch: _QueryCapture) -> None:
        handler.search(AgentSearchReq(project_id="p1", query="x", limit=5000))
        assert 1000 in ch.calls[0][1].values()


# ============================================================================
# Query builder helpers
# ============================================================================


class TestQueryBuilderHelpers:
    def test_build_order_by_default(self) -> None:
        assert (
            build_order_by(None, SPAN_SORTABLE_COLS, "started_at DESC")
            == "started_at DESC"
        )

    def test_build_order_by_valid(self) -> None:
        sort = [AgentSortBy(field="input_tokens", direction="asc")]
        assert (
            build_order_by(sort, SPAN_SORTABLE_COLS, "fallback") == "input_tokens asc"
        )

    def test_build_order_by_rejects_invalid(self) -> None:
        sort = [AgentSortBy(field="'; DROP TABLE--", direction="asc")]
        assert (
            build_order_by(sort, SPAN_SORTABLE_COLS, "started_at DESC")
            == "started_at DESC"
        )

    def test_build_order_by_multiple(self) -> None:
        sort = [
            AgentSortBy(field="started_at", direction="desc"),
            AgentSortBy(field="input_tokens", direction="asc"),
        ]
        assert (
            build_order_by(sort, SPAN_SORTABLE_COLS, "fallback")
            == "started_at desc, input_tokens asc"
        )


# ============================================================================
# SQL injection safety
# ============================================================================


class TestSQLInjectionSafety:
    def test_sort_injection(
        self, handler: AgentQueryHandler, ch: _QueryCapture
    ) -> None:
        handler.spans_query(
            AgentSpansQueryReq(
                project_id="p1",
                sort_by=[
                    AgentSortBy(
                        field="started_at; DROP TABLE spans--", direction="desc"
                    )
                ],
            )
        )
        assert "DROP" not in ch.calls[1][0]
        assert "ORDER BY started_at DESC" in ch.calls[1][0]

    def test_custom_attr_key_parameterized(
        self, handler: AgentQueryHandler, ch: _QueryCapture
    ) -> None:
        handler.spans_query(
            AgentSpansQueryReq(
                project_id="p1",
                filters=AgentSpansQueryFilters(
                    custom_filters=[
                        AgentCustomAttrFilter(
                            attr_key="'; DROP TABLE--", operator="eq", value="x"
                        )
                    ]
                ),
            )
        )
        assert "DROP TABLE" not in ch.calls[1][0]
        assert "'; DROP TABLE--" in ch.calls[1][1].values()

    def test_filter_values_parameterized(
        self, handler: AgentQueryHandler, ch: _QueryCapture
    ) -> None:
        handler.spans_query(
            AgentSpansQueryReq(
                project_id="'; DROP TABLE--",
                filters=AgentSpansQueryFilters(agent_name="'; DROP TABLE--"),
            )
        )
        assert "DROP TABLE" not in ch.calls[1][0]
