/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesContent } from "../funcs/filesContent.js";
import { filesCreate } from "../funcs/filesCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Files extends ClientSDK {
  /**
   * File Create
   */
  async create(
    request: components.BodyFileCreateFileCreatePost,
    options?: RequestOptions,
  ): Promise<components.FileCreateRes> {
    return unwrapAsync(filesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * File Content
   */
  async content(
    request: components.FileContentReadReq,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(filesContent(
      this,
      request,
      options,
    ));
  }
}
