/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { objectsCreate } from "../funcs/objectsCreate.js";
import { objectsQuery } from "../funcs/objectsQuery.js";
import { objectsRead } from "../funcs/objectsRead.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Objects extends ClientSDK {
  /**
   * Obj Create
   */
  async create(
    request: components.ObjCreateReq,
    options?: RequestOptions,
  ): Promise<components.ObjCreateRes> {
    return unwrapAsync(objectsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Obj Read
   */
  async read(
    request: components.ObjReadReq,
    options?: RequestOptions,
  ): Promise<components.ObjReadRes> {
    return unwrapAsync(objectsRead(
      this,
      request,
      options,
    ));
  }

  /**
   * Objs Query
   */
  async query(
    request: components.ObjQueryReq,
    options?: RequestOptions,
  ): Promise<components.ObjQueryRes> {
    return unwrapAsync(objectsQuery(
      this,
      request,
      options,
    ));
  }
}
