/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { refsReadBatch } from "../funcs/refsReadBatch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Refs extends ClientSDK {
  /**
   * Refs Read Batch
   */
  async readBatch(
    request: components.RefsReadBatchReq,
    options?: RequestOptions,
  ): Promise<components.RefsReadBatchRes> {
    return unwrapAsync(refsReadBatch(
      this,
      request,
      options,
    ));
  }
}
