/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serviceGetHealth } from "../funcs/serviceGetHealth.js";
import { serviceGetServerInfo } from "../funcs/serviceGetServerInfo.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Service extends ClientSDK {
  /**
   * Read Root
   */
  async getHealth(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(serviceGetHealth(
      this,
      options,
    ));
  }

  /**
   * Server Info
   */
  async getServerInfo(
    options?: RequestOptions,
  ): Promise<components.ServerInfoRes> {
    return unwrapAsync(serviceGetServerInfo(
      this,
      options,
    ));
  }
}
