/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tablesCreate } from "../funcs/tablesCreate.js";
import { tablesQuery } from "../funcs/tablesQuery.js";
import { tablesQueryStats } from "../funcs/tablesQueryStats.js";
import { tablesUpdate } from "../funcs/tablesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tables extends ClientSDK {
  /**
   * Table Create
   */
  async create(
    request: components.TableCreateReq,
    options?: RequestOptions,
  ): Promise<components.TableCreateRes> {
    return unwrapAsync(tablesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Table Update
   */
  async update(
    request: components.TableUpdateReq,
    options?: RequestOptions,
  ): Promise<components.TableUpdateRes> {
    return unwrapAsync(tablesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Table Query
   */
  async query(
    request: components.TableQueryReq,
    options?: RequestOptions,
  ): Promise<components.TableQueryRes> {
    return unwrapAsync(tablesQuery(
      this,
      request,
      options,
    ));
  }

  /**
   * Table Query Stats
   */
  async queryStats(
    request: components.TableQueryStatsReq,
    options?: RequestOptions,
  ): Promise<components.TableQueryStatsRes> {
    return unwrapAsync(tablesQueryStats(
      this,
      request,
      options,
    ));
  }
}
