name: 🛠️ Feature Request
description: Suggest an idea to help us improve Weave
title: "[Feature]: "
labels:
  - "enhancement"

body:
  - type: markdown
    attributes:
      value: >
        **Thanks :heart: for taking the time to fill out this feature request report!** We kindly ask that you search to
        see if an issue [already exists](https://github.com/wandb/weave/issues?q=is%3Aissue+sort%3Acreated-desc+) for
        your feature.

        We are also happy to accept contributions from our users. For more details see
        [here](https://github.com/wandb/weave/blob/master/CONTRIBUTING.md).

  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of the feature you're interested in.
      value: |
        <!--- Describe your feature here --->
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Solution
      description: >
        Describe the solution you'd like. A clear and concise description of what you want to happen. If you have
        considered alternatives, please describe them.
      value: |
        <!--- Describe your solution here --->
    validations:
      required: false

  - type: input
    attributes:
      label: Weave Project Link
      description: >
        If applicable, please provide a link to your Weave project (e.g., https://wandb.ai/your-entity/your-project/weave)
        to help us understand the context of your feature request.
      placeholder: "https://wandb.ai/entity/project/weave"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots or Mockups
      description: >
        If applicable, add screenshots or mockups to help illustrate your feature request. You can drag and drop images
        here or paste them directly into this field.
      placeholder: "Drag and drop screenshots/mockups here or paste image URLs"
    validations:
      required: false
