/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { collectExtraKeys as collectExtraKeys$ } from "../../lib/schemas.js";

/**
 * Timeouts occurred with the request
 */
export type TimeoutData = {
  message?: string | undefined;

  additionalProperties: { [k: string]: any };
};

/**
 * Timeouts occurred with the request
 */
export class Timeout extends Error {
  additionalProperties: { [k: string]: any } = {};

  /** The original data that was passed to this error instance. */
  data$: TimeoutData;

  constructor(err: TimeoutData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.additionalProperties != null) {
      this.additionalProperties = err.additionalProperties;
    }

    this.name = "Timeout";
  }
}

/** @internal */
export const Timeout$inboundSchema: z.ZodType<Timeout, z.ZodTypeDef, unknown> =
  collectExtraKeys$(
    z.object({
      message: z.string().optional(),
    })
      .catchall(z.any()),
    "additionalProperties",
  )
    .transform((v) => {
      return new Timeout(v);
    });

/** @internal */
export type Timeout$Outbound = {
  message?: string | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const Timeout$outboundSchema: z.ZodType<
  Timeout$Outbound,
  z.ZodTypeDef,
  Timeout
> = z.instanceof(Timeout)
  .transform(v => v.data$)
  .pipe(
    z.object({
      message: z.string().optional(),
      additionalProperties: z.record(z.any()),
    }).transform((v) => {
      return {
        ...v.additionalProperties,
        ...remap$(v, {
          additionalProperties: null,
        }),
      };
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Timeout$ {
  /** @deprecated use `Timeout$inboundSchema` instead. */
  export const inboundSchema = Timeout$inboundSchema;
  /** @deprecated use `Timeout$outboundSchema` instead. */
  export const outboundSchema = Timeout$outboundSchema;
  /** @deprecated use `Timeout$Outbound` instead. */
  export type Outbound = Timeout$Outbound;
}
