/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { callsDelete } from "../funcs/callsDelete.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CallsDeleteMutationVariables = {
  request: components.CallsDeleteReq;
  options?: RequestOptions;
};

export type CallsDeleteMutationData = components.CallsDeleteRes;

/**
 * Calls Delete
 */
export function useCallsDeleteMutation(
  options?: MutationHookOptions<
    CallsDeleteMutationData,
    Error,
    CallsDeleteMutationVariables
  >,
): UseMutationResult<
  CallsDeleteMutationData,
  Error,
  CallsDeleteMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildCallsDeleteMutation(client, options),
    ...options,
  });
}

export function mutationKeyCallsDelete(): MutationKey {
  return ["wandb", "Calls", "delete"];
}

export function buildCallsDeleteMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CallsDeleteMutationVariables,
  ) => Promise<CallsDeleteMutationData>;
} {
  return {
    mutationKey: mutationKeyCallsDelete(),
    mutationFn: function callsDeleteMutationFn({
      request,
      options,
    }): Promise<CallsDeleteMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(callsDelete(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
