/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { callsUpdate } from "../funcs/callsUpdate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CallsUpdateMutationVariables = {
  request: components.CallUpdateReq;
  options?: RequestOptions;
};

export type CallsUpdateMutationData = components.CallUpdateRes;

/**
 * Call Update
 */
export function useCallsUpdateMutation(
  options?: MutationHookOptions<
    CallsUpdateMutationData,
    Error,
    CallsUpdateMutationVariables
  >,
): UseMutationResult<
  CallsUpdateMutationData,
  Error,
  CallsUpdateMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildCallsUpdateMutation(client, options),
    ...options,
  });
}

export function mutationKeyCallsUpdate(): MutationKey {
  return ["wandb", "Calls", "update"];
}

export function buildCallsUpdateMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CallsUpdateMutationVariables,
  ) => Promise<CallsUpdateMutationData>;
} {
  return {
    mutationKey: mutationKeyCallsUpdate(),
    mutationFn: function callsUpdateMutationFn({
      request,
      options,
    }): Promise<CallsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(callsUpdate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
