/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { callsUpsertBatch } from "../funcs/callsUpsertBatch.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CallsUpsertBatchMutationVariables = {
  request: components.CallCreateBatchReq;
  options?: RequestOptions;
};

export type CallsUpsertBatchMutationData = components.CallCreateBatchRes;

/**
 * Call Start Batch
 */
export function useCallsUpsertBatchMutation(
  options?: MutationHookOptions<
    CallsUpsertBatchMutationData,
    Error,
    CallsUpsertBatchMutationVariables
  >,
): UseMutationResult<
  CallsUpsertBatchMutationData,
  Error,
  CallsUpsertBatchMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildCallsUpsertBatchMutation(client, options),
    ...options,
  });
}

export function mutationKeyCallsUpsertBatch(): MutationKey {
  return ["wandb", "Calls", "upsertBatch"];
}

export function buildCallsUpsertBatchMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CallsUpsertBatchMutationVariables,
  ) => Promise<CallsUpsertBatchMutationData>;
} {
  return {
    mutationKey: mutationKeyCallsUpsertBatch(),
    mutationFn: function callsUpsertBatchMutationFn({
      request,
      options,
    }): Promise<CallsUpsertBatchMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(callsUpsertBatch(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
