/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { callsStreamQuery } from "../funcs/callsStreamQuery.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CallsStreamQueryMutationVariables = {
  request: components.CallsQueryReq;
  options?: RequestOptions;
};

export type CallsStreamQueryMutationData = any;

/**
 * Calls Query Stream
 */
export function useCallsStreamQueryMutation(
  options?: MutationHookOptions<
    CallsStreamQueryMutationData,
    Error,
    CallsStreamQueryMutationVariables
  >,
): UseMutationResult<
  CallsStreamQueryMutationData,
  Error,
  CallsStreamQueryMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildCallsStreamQueryMutation(client, options),
    ...options,
  });
}

export function mutationKeyCallsStreamQuery(): MutationKey {
  return ["wandb", "Calls", "streamQuery"];
}

export function buildCallsStreamQueryMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CallsStreamQueryMutationVariables,
  ) => Promise<CallsStreamQueryMutationData>;
} {
  return {
    mutationKey: mutationKeyCallsStreamQuery(),
    mutationFn: function callsStreamQueryMutationFn({
      request,
      options,
    }): Promise<CallsStreamQueryMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(callsStreamQuery(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
