/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { callsEnd } from "../funcs/callsEnd.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CallsEndMutationVariables = {
  request: components.CallEndReq;
  options?: RequestOptions;
};

export type CallsEndMutationData = components.CallEndRes;

/**
 * Call End
 */
export function useCallsEndMutation(
  options?: MutationHookOptions<
    CallsEndMutationData,
    Error,
    CallsEndMutationVariables
  >,
): UseMutationResult<CallsEndMutationData, Error, CallsEndMutationVariables> {
  const client = useWandbContext();
  return useMutation({
    ...buildCallsEndMutation(client, options),
    ...options,
  });
}

export function mutationKeyCallsEnd(): MutationKey {
  return ["wandb", "Calls", "end"];
}

export function buildCallsEndMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CallsEndMutationVariables,
  ) => Promise<CallsEndMutationData>;
} {
  return {
    mutationKey: mutationKeyCallsEnd(),
    mutationFn: function callsEndMutationFn({
      request,
      options,
    }): Promise<CallsEndMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(callsEnd(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
