/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { costsCreate } from "../funcs/costsCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CostsCreateMutationVariables = {
  request: components.CostCreateReq;
  options?: RequestOptions;
};

export type CostsCreateMutationData = components.CostCreateRes;

/**
 * Cost Create
 */
export function useCostsCreateMutation(
  options?: MutationHookOptions<
    CostsCreateMutationData,
    Error,
    CostsCreateMutationVariables
  >,
): UseMutationResult<
  CostsCreateMutationData,
  Error,
  CostsCreateMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildCostsCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyCostsCreate(): MutationKey {
  return ["wandb", "Costs", "create"];
}

export function buildCostsCreateMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CostsCreateMutationVariables,
  ) => Promise<CostsCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyCostsCreate(),
    mutationFn: function costsCreateMutationFn({
      request,
      options,
    }): Promise<CostsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(costsCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
