/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { costsPurge } from "../funcs/costsPurge.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CostsPurgeMutationVariables = {
  request: components.CostPurgeReq;
  options?: RequestOptions;
};

export type CostsPurgeMutationData = components.CostPurgeRes;

/**
 * Cost Purge
 */
export function useCostsPurgeMutation(
  options?: MutationHookOptions<
    CostsPurgeMutationData,
    Error,
    CostsPurgeMutationVariables
  >,
): UseMutationResult<
  CostsPurgeMutationData,
  Error,
  CostsPurgeMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildCostsPurgeMutation(client, options),
    ...options,
  });
}

export function mutationKeyCostsPurge(): MutationKey {
  return ["wandb", "Costs", "purge"];
}

export function buildCostsPurgeMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CostsPurgeMutationVariables,
  ) => Promise<CostsPurgeMutationData>;
} {
  return {
    mutationKey: mutationKeyCostsPurge(),
    mutationFn: function costsPurgeMutationFn({
      request,
      options,
    }): Promise<CostsPurgeMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(costsPurge(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
