/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { costsQuery } from "../funcs/costsQuery.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CostsQueryMutationVariables = {
  request: components.CostQueryReq;
  options?: RequestOptions;
};

export type CostsQueryMutationData = components.CostQueryRes;

/**
 * Cost Query
 */
export function useCostsQueryMutation(
  options?: MutationHookOptions<
    CostsQueryMutationData,
    Error,
    CostsQueryMutationVariables
  >,
): UseMutationResult<
  CostsQueryMutationData,
  Error,
  CostsQueryMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildCostsQueryMutation(client, options),
    ...options,
  });
}

export function mutationKeyCostsQuery(): MutationKey {
  return ["wandb", "Costs", "query"];
}

export function buildCostsQueryMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CostsQueryMutationVariables,
  ) => Promise<CostsQueryMutationData>;
} {
  return {
    mutationKey: mutationKeyCostsQuery(),
    mutationFn: function costsQueryMutationFn({
      request,
      options,
    }): Promise<CostsQueryMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(costsQuery(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
