/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { feedbackPurge } from "../funcs/feedbackPurge.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type FeedbackPurgeMutationVariables = {
  request: components.FeedbackPurgeReq;
  options?: RequestOptions;
};

export type FeedbackPurgeMutationData = components.FeedbackPurgeRes;

/**
 * Feedback Purge
 *
 * @remarks
 * Permanently delete feedback.
 */
export function useFeedbackPurgeMutation(
  options?: MutationHookOptions<
    FeedbackPurgeMutationData,
    Error,
    FeedbackPurgeMutationVariables
  >,
): UseMutationResult<
  FeedbackPurgeMutationData,
  Error,
  FeedbackPurgeMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildFeedbackPurgeMutation(client, options),
    ...options,
  });
}

export function mutationKeyFeedbackPurge(): MutationKey {
  return ["wandb", "Feedback", "purge"];
}

export function buildFeedbackPurgeMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: FeedbackPurgeMutationVariables,
  ) => Promise<FeedbackPurgeMutationData>;
} {
  return {
    mutationKey: mutationKeyFeedbackPurge(),
    mutationFn: function feedbackPurgeMutationFn({
      request,
      options,
    }): Promise<FeedbackPurgeMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(feedbackPurge(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
