/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { feedbackCreate } from "../funcs/feedbackCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type FeedbackCreateMutationVariables = {
  request: components.FeedbackCreateReq;
  options?: RequestOptions;
};

export type FeedbackCreateMutationData = components.FeedbackCreateRes;

/**
 * Feedback Create
 *
 * @remarks
 * Add feedback to a call or object.
 */
export function useFeedbackCreateMutation(
  options?: MutationHookOptions<
    FeedbackCreateMutationData,
    Error,
    FeedbackCreateMutationVariables
  >,
): UseMutationResult<
  FeedbackCreateMutationData,
  Error,
  FeedbackCreateMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildFeedbackCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyFeedbackCreate(): MutationKey {
  return ["wandb", "Feedback", "create"];
}

export function buildFeedbackCreateMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: FeedbackCreateMutationVariables,
  ) => Promise<FeedbackCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyFeedbackCreate(),
    mutationFn: function feedbackCreateMutationFn({
      request,
      options,
    }): Promise<FeedbackCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(feedbackCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
