/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { filesCreate } from "../funcs/filesCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type FilesCreateMutationVariables = {
  request: components.BodyFileCreateFileCreatePost;
  options?: RequestOptions;
};

export type FilesCreateMutationData = components.FileCreateRes;

/**
 * File Create
 */
export function useFilesCreateMutation(
  options?: MutationHookOptions<
    FilesCreateMutationData,
    Error,
    FilesCreateMutationVariables
  >,
): UseMutationResult<
  FilesCreateMutationData,
  Error,
  FilesCreateMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildFilesCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyFilesCreate(): MutationKey {
  return ["wandb", "Files", "create"];
}

export function buildFilesCreateMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: FilesCreateMutationVariables,
  ) => Promise<FilesCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyFilesCreate(),
    mutationFn: function filesCreateMutationFn({
      request,
      options,
    }): Promise<FilesCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(filesCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
