/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { filesContent } from "../funcs/filesContent.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type FilesContentMutationVariables = {
  request: components.FileContentReadReq;
  options?: RequestOptions;
};

export type FilesContentMutationData = any;

/**
 * File Content
 */
export function useFilesContentMutation(
  options?: MutationHookOptions<
    FilesContentMutationData,
    Error,
    FilesContentMutationVariables
  >,
): UseMutationResult<
  FilesContentMutationData,
  Error,
  FilesContentMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildFilesContentMutation(client, options),
    ...options,
  });
}

export function mutationKeyFilesContent(): MutationKey {
  return ["wandb", "Files", "content"];
}

export function buildFilesContentMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: FilesContentMutationVariables,
  ) => Promise<FilesContentMutationData>;
} {
  return {
    mutationKey: mutationKeyFilesContent(),
    mutationFn: function filesContentMutationFn({
      request,
      options,
    }): Promise<FilesContentMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(filesContent(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
