/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { objectsCreate } from "../funcs/objectsCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ObjectsCreateMutationVariables = {
  request: components.ObjCreateReq;
  options?: RequestOptions;
};

export type ObjectsCreateMutationData = components.ObjCreateRes;

/**
 * Obj Create
 */
export function useObjectsCreateMutation(
  options?: MutationHookOptions<
    ObjectsCreateMutationData,
    Error,
    ObjectsCreateMutationVariables
  >,
): UseMutationResult<
  ObjectsCreateMutationData,
  Error,
  ObjectsCreateMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildObjectsCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyObjectsCreate(): MutationKey {
  return ["wandb", "Objects", "create"];
}

export function buildObjectsCreateMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ObjectsCreateMutationVariables,
  ) => Promise<ObjectsCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyObjectsCreate(),
    mutationFn: function objectsCreateMutationFn({
      request,
      options,
    }): Promise<ObjectsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(objectsCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
