/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { objectsRead } from "../funcs/objectsRead.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ObjectsReadMutationVariables = {
  request: components.ObjReadReq;
  options?: RequestOptions;
};

export type ObjectsReadMutationData = components.ObjReadRes;

/**
 * Obj Read
 */
export function useObjectsReadMutation(
  options?: MutationHookOptions<
    ObjectsReadMutationData,
    Error,
    ObjectsReadMutationVariables
  >,
): UseMutationResult<
  ObjectsReadMutationData,
  Error,
  ObjectsReadMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildObjectsReadMutation(client, options),
    ...options,
  });
}

export function mutationKeyObjectsRead(): MutationKey {
  return ["wandb", "Objects", "read"];
}

export function buildObjectsReadMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ObjectsReadMutationVariables,
  ) => Promise<ObjectsReadMutationData>;
} {
  return {
    mutationKey: mutationKeyObjectsRead(),
    mutationFn: function objectsReadMutationFn({
      request,
      options,
    }): Promise<ObjectsReadMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(objectsRead(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
