/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { objectsQuery } from "../funcs/objectsQuery.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ObjectsQueryMutationVariables = {
  request: components.ObjQueryReq;
  options?: RequestOptions;
};

export type ObjectsQueryMutationData = components.ObjQueryRes;

/**
 * Objs Query
 */
export function useObjectsQueryMutation(
  options?: MutationHookOptions<
    ObjectsQueryMutationData,
    Error,
    ObjectsQueryMutationVariables
  >,
): UseMutationResult<
  ObjectsQueryMutationData,
  Error,
  ObjectsQueryMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildObjectsQueryMutation(client, options),
    ...options,
  });
}

export function mutationKeyObjectsQuery(): MutationKey {
  return ["wandb", "Objects", "query"];
}

export function buildObjectsQueryMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ObjectsQueryMutationVariables,
  ) => Promise<ObjectsQueryMutationData>;
} {
  return {
    mutationKey: mutationKeyObjectsQuery(),
    mutationFn: function objectsQueryMutationFn({
      request,
      options,
    }): Promise<ObjectsQueryMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(objectsQuery(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
