/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { refsReadBatch } from "../funcs/refsReadBatch.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type RefsReadBatchMutationVariables = {
  request: components.RefsReadBatchReq;
  options?: RequestOptions;
};

export type RefsReadBatchMutationData = components.RefsReadBatchRes;

/**
 * Refs Read Batch
 */
export function useRefsReadBatchMutation(
  options?: MutationHookOptions<
    RefsReadBatchMutationData,
    Error,
    RefsReadBatchMutationVariables
  >,
): UseMutationResult<
  RefsReadBatchMutationData,
  Error,
  RefsReadBatchMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildRefsReadBatchMutation(client, options),
    ...options,
  });
}

export function mutationKeyRefsReadBatch(): MutationKey {
  return ["wandb", "Refs", "readBatch"];
}

export function buildRefsReadBatchMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: RefsReadBatchMutationVariables,
  ) => Promise<RefsReadBatchMutationData>;
} {
  return {
    mutationKey: mutationKeyRefsReadBatch(),
    mutationFn: function refsReadBatchMutationFn({
      request,
      options,
    }): Promise<RefsReadBatchMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(refsReadBatch(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
