/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { serviceGetHealth } from "../funcs/serviceGetHealth.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";

export type ServiceGetHealthQueryData = any;

/**
 * Read Root
 */
export function useServiceGetHealth(
  options?: QueryHookOptions<ServiceGetHealthQueryData>,
): UseQueryResult<ServiceGetHealthQueryData, Error> {
  const client = useWandbContext();
  return useQuery({
    ...buildServiceGetHealthQuery(
      client,
      options,
    ),
    ...options,
  });
}

/**
 * Read Root
 */
export function useServiceGetHealthSuspense(
  options?: SuspenseQueryHookOptions<ServiceGetHealthQueryData>,
): UseSuspenseQueryResult<ServiceGetHealthQueryData, Error> {
  const client = useWandbContext();
  return useSuspenseQuery({
    ...buildServiceGetHealthQuery(
      client,
      options,
    ),
    ...options,
  });
}

export function prefetchServiceGetHealth(
  queryClient: QueryClient,
  client$: WandbCore,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildServiceGetHealthQuery(
      client$,
    ),
  });
}

export function setServiceGetHealthData(
  client: QueryClient,
  data: ServiceGetHealthQueryData,
): ServiceGetHealthQueryData | undefined {
  const key = queryKeyServiceGetHealth();

  return client.setQueryData<ServiceGetHealthQueryData>(key, data);
}

export function invalidateAllServiceGetHealth(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["wandb", "Service", "getHealth"],
  });
}

export function buildServiceGetHealthQuery(
  client$: WandbCore,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ServiceGetHealthQueryData>;
} {
  return {
    queryKey: queryKeyServiceGetHealth(),
    queryFn: async function serviceGetHealthQueryFn(
      ctx,
    ): Promise<ServiceGetHealthQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(serviceGetHealth(
        client$,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyServiceGetHealth(): QueryKey {
  return ["wandb", "Service", "getHealth"];
}
