/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { tablesQuery } from "../funcs/tablesQuery.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type TablesQueryMutationVariables = {
  request: components.TableQueryReq;
  options?: RequestOptions;
};

export type TablesQueryMutationData = components.TableQueryRes;

/**
 * Table Query
 */
export function useTablesQueryMutation(
  options?: MutationHookOptions<
    TablesQueryMutationData,
    Error,
    TablesQueryMutationVariables
  >,
): UseMutationResult<
  TablesQueryMutationData,
  Error,
  TablesQueryMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildTablesQueryMutation(client, options),
    ...options,
  });
}

export function mutationKeyTablesQuery(): MutationKey {
  return ["wandb", "Tables", "query"];
}

export function buildTablesQueryMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: TablesQueryMutationVariables,
  ) => Promise<TablesQueryMutationData>;
} {
  return {
    mutationKey: mutationKeyTablesQuery(),
    mutationFn: function tablesQueryMutationFn({
      request,
      options,
    }): Promise<TablesQueryMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(tablesQuery(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
