/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { WandbCore } from "../core.js";
import { tablesQueryStats } from "../funcs/tablesQueryStats.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useWandbContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type TablesQueryStatsMutationVariables = {
  request: components.TableQueryStatsReq;
  options?: RequestOptions;
};

export type TablesQueryStatsMutationData = components.TableQueryStatsRes;

/**
 * Table Query Stats
 */
export function useTablesQueryStatsMutation(
  options?: MutationHookOptions<
    TablesQueryStatsMutationData,
    Error,
    TablesQueryStatsMutationVariables
  >,
): UseMutationResult<
  TablesQueryStatsMutationData,
  Error,
  TablesQueryStatsMutationVariables
> {
  const client = useWandbContext();
  return useMutation({
    ...buildTablesQueryStatsMutation(client, options),
    ...options,
  });
}

export function mutationKeyTablesQueryStats(): MutationKey {
  return ["wandb", "Tables", "queryStats"];
}

export function buildTablesQueryStatsMutation(
  client$: WandbCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: TablesQueryStatsMutationVariables,
  ) => Promise<TablesQueryStatsMutationData>;
} {
  return {
    mutationKey: mutationKeyTablesQueryStats(),
    mutationFn: function tablesQueryStatsMutationFn({
      request,
      options,
    }): Promise<TablesQueryStatsMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(tablesQueryStats(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
