"""The client's view of a trace server.

This protocol is owned by the client and typed entirely with the models in
``weave.trace_server_bindings.models`` — the OpenAPI-generated
``weave_server_sdk.models`` (the source of truth, re-exported) plus a handful
of gap models for surface the published SDK does not yet express. The ``tsi``
alias is a temporary migration aid; the follow-up PR imports the models
directly.

It deliberately contains only the methods the client (WeaveClient, flow
modules, caching middleware, WAL) actually uses. Server implementations may —
and do — expose more; extra methods reach callers through the delegation
mixin's passthrough rather than this contract.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Protocol

from weave.trace_server_bindings import models as tsi
from weave.trace_server_bindings.async_batch_processor import AsyncBatchProcessor
from weave.trace_server_bindings.call_batch_processor import CallBatchProcessor


class TraceServerClientInterface(Protocol):
    """What the Weave client requires of a trace server."""

    # ---- service ----------------------------------------------------------

    def ensure_project_exists(
        self, entity: str, project: str
    ) -> tsi.EnsureProjectExistsRes: ...
    def set_auth(self, auth: tuple[str, str]) -> None: ...
    def get_call_processor(
        self,
    ) -> AsyncBatchProcessor | CallBatchProcessor | None: ...
    def get_feedback_processor(self) -> AsyncBatchProcessor | None: ...
    def server_info(self) -> tsi.ServerInfoRes: ...
    def projects_info(self, req: tsi.ProjectsInfoReq) -> list[tsi.ProjectsInfoRes]: ...

    # ---- calls -------------------------------------------------------------

    def call_start(self, req: tsi.CallStartReq) -> tsi.CallStartRes: ...
    def call_end(self, req: tsi.CallEndReq) -> tsi.CallEndRes: ...
    def call_update(self, req: tsi.CallUpdateReq) -> tsi.CallUpdateRes: ...
    def calls_delete(self, req: tsi.CallsDeleteReq) -> tsi.CallsDeleteRes: ...
    def calls_query_stream(
        self, req: tsi.CallsQueryReq
    ) -> Iterator[tsi.CallSchema]: ...
    def calls_query_stats(
        self, req: tsi.CallsQueryStatsReq
    ) -> tsi.CallsQueryStatsRes: ...

    # ---- objects -----------------------------------------------------------

    def obj_create(self, req: tsi.ObjCreateReq) -> tsi.ObjCreateRes: ...
    def obj_read(self, req: tsi.ObjReadReq) -> tsi.ObjReadRes: ...
    def objs_query(self, req: tsi.ObjQueryReq) -> tsi.ObjQueryRes: ...
    def obj_delete(self, req: tsi.ObjDeleteReq) -> tsi.ObjDeleteRes: ...

    # Request envelopes for these come from bindings models (the OpenAPI spec
    # carries the ids in the URL path, so the SDK has body models only).
    def obj_add_tags(self, req: tsi.ObjAddTagsReq) -> tsi.ObjAddTagsRes: ...
    def obj_remove_tags(self, req: tsi.ObjRemoveTagsReq) -> tsi.ObjRemoveTagsRes: ...
    def obj_set_aliases(self, req: tsi.ObjSetAliasesReq) -> tsi.ObjSetAliasesRes: ...
    def obj_remove_aliases(
        self, req: tsi.ObjRemoveAliasesReq
    ) -> tsi.ObjRemoveAliasesRes: ...
    def tags_list(self, req: tsi.TagsListReq) -> tsi.TagsListRes: ...
    def aliases_list(self, req: tsi.AliasesListReq) -> tsi.AliasesListRes: ...

    # ---- tables ------------------------------------------------------------

    def table_create(self, req: tsi.TableCreateReq) -> tsi.TableCreateRes: ...
    def table_update(self, req: tsi.TableUpdateReq) -> tsi.TableUpdateRes: ...
    def table_query(self, req: tsi.TableQueryReq) -> tsi.TableQueryRes: ...
    def table_query_stats(
        self, req: tsi.TableQueryStatsReq
    ) -> tsi.TableQueryStatsRes: ...
    def table_query_stats_batch(
        self, req: tsi.TableQueryStatsBatchReq
    ) -> tsi.TableQueryStatsBatchRes: ...
    def table_create_from_digests(
        self, req: tsi.TableCreateFromDigestsReq
    ) -> tsi.TableCreateFromDigestsRes: ...

    # ---- refs / files ------------------------------------------------------

    def refs_read_batch(self, req: tsi.RefsReadBatchReq) -> tsi.RefsReadBatchRes: ...
    def file_create(self, req: tsi.FileCreateReq) -> tsi.FileCreateRes: ...
    def file_content_read(
        self, req: tsi.FileContentReadReq
    ) -> tsi.FileContentReadRes: ...
    def files_stats(self, req: tsi.FilesStatsReq) -> tsi.FilesStatsRes: ...

    # ---- feedback ----------------------------------------------------------

    def feedback_create(self, req: tsi.FeedbackCreateReq) -> tsi.FeedbackCreateRes: ...
    def feedback_query(self, req: tsi.FeedbackQueryReq) -> tsi.FeedbackQueryRes: ...
    def feedback_purge(self, req: tsi.FeedbackPurgeReq) -> tsi.FeedbackPurgeRes: ...

    # ---- costs --------------------------------------------------------------

    def cost_create(self, req: tsi.CostCreateReq) -> tsi.CostCreateRes: ...
    def cost_query(self, req: tsi.CostQueryReq) -> tsi.CostQueryRes: ...
    def cost_purge(self, req: tsi.CostPurgeReq) -> tsi.CostPurgeRes: ...

    # ---- annotation queues ---------------------------------------------------

    def annotation_queue_create(
        self, req: tsi.AnnotationQueueCreateReq
    ) -> tsi.AnnotationQueueCreateRes: ...
    def annotation_queues_query_stream(
        self, req: tsi.AnnotationQueuesQueryReq
    ) -> Iterator[tsi.AnnotationQueueSchema]: ...
    def annotation_queue_read(
        self, req: tsi.AnnotationQueueReadReq
    ) -> tsi.AnnotationQueueReadRes: ...
    def annotation_queue_delete(
        self, req: tsi.AnnotationQueueDeleteReq
    ) -> tsi.AnnotationQueueDeleteRes: ...
    def annotation_queue_update(
        self, req: tsi.AnnotationQueueUpdateReq
    ) -> tsi.AnnotationQueueUpdateRes: ...
    def annotation_queue_add_calls(
        self, req: tsi.AnnotationQueueAddCallsReq
    ) -> tsi.AnnotationQueueAddCallsRes: ...
    def annotation_queue_items_query(
        self, req: tsi.AnnotationQueueItemsQueryReq
    ) -> tsi.AnnotationQueueItemsQueryRes: ...
    def annotation_queues_stats(
        self, req: tsi.AnnotationQueuesStatsReq
    ) -> tsi.AnnotationQueuesStatsRes: ...

    # ---- completions ----------------------------------------------------------

    def completions_create(
        self, req: tsi.CompletionsCreateReq
    ) -> tsi.CompletionsCreateRes: ...
