"""Generate canonical serialization payloads from Python SDK's to_json.

Each payload is written as an individual JSON file under
tests/cross_sdk/canonical_serialization/. These files are the source of
truth for cross-SDK serialization parity.

Usage:
    # Generate/update payloads:
    python scripts/generate_serialization_fixtures.py

    # Check payloads are up-to-date (CI mode):
    python scripts/generate_serialization_fixtures.py --check
"""

from __future__ import annotations

import datetime
import difflib
import json
import sys
from collections import namedtuple
from contextlib import contextmanager
from pathlib import Path
from unittest.mock import MagicMock, patch

from weave.trace.object_record import ObjectRecord
from weave.trace.refs import ObjectRef, OpRef, TableRef
from weave.trace.serialization.serialize import to_json

REPO_ROOT = Path(__file__).parent.parent
CANONICAL_DIR = REPO_ROOT / "tests" / "cross_sdk" / "canonical_serialization"
PROJECT_ID = "test-entity/test-project"


def _make_mock_client() -> MagicMock:
    """Mock WeaveClient for both to_json's client param and the global context.

    - _send_file_create: no-op (digest is computed locally from bytes)
    - _save_op: returns a mock ref with a stable URI (for custom type load ops)
    """
    client = MagicMock()
    client._send_file_create = MagicMock()

    mock_ref = MagicMock()
    mock_ref.uri = "weave:///test-entity/test-project/op/mock_load_op:mock_digest"
    client._save_op = MagicMock(return_value=mock_ref)
    return client


@contextmanager
def _mock_weave_context(client: MagicMock):
    """Patch the global weave client so encode_custom_obj can save load ops."""
    with patch(
        "weave.trace.serialization.custom_objs.require_weave_client",
        return_value=client,
    ):
        yield


def generate_payloads() -> dict[str, dict]:
    """Run representative inputs through to_json and capture the output.

    Returns a dict of {filename_stem: payload_dict}. Each payload has:
      - description: what this tests
      - output: the exact JSON-serializable value to_json returns
      - static (optional): True if manually defined (not generated by to_json)
    """
    client = _make_mock_client()
    payloads: dict[str, dict] = {}

    # ── Primitives ──────────────────────────────────────────────────────
    payloads["primitive_int"] = {
        "description": "Integer value",
        "output": to_json(42, PROJECT_ID, client),
    }
    payloads["primitive_float"] = {
        "description": "Float value",
        "output": to_json(3.14, PROJECT_ID, client),
    }
    payloads["primitive_string"] = {
        "description": "String value",
        "output": to_json("hello world", PROJECT_ID, client),
    }
    payloads["primitive_bool_true"] = {
        "description": "Boolean true",
        "output": to_json(True, PROJECT_ID, client),
    }
    payloads["primitive_bool_false"] = {
        "description": "Boolean false",
        "output": to_json(False, PROJECT_ID, client),
    }
    payloads["primitive_none"] = {
        "description": "None/null value",
        "output": to_json(None, PROJECT_ID, client),
    }

    # ── Collections ─────────────────────────────────────────────────────
    payloads["list_of_primitives"] = {
        "description": "List of mixed primitives",
        "output": to_json([1, "two", 3.0, True, None], PROJECT_ID, client),
    }
    payloads["nested_dict"] = {
        "description": "Nested dictionary",
        "output": to_json(
            {"a": 1, "b": {"c": 2, "d": [3, 4]}, "e": None},
            PROJECT_ID,
            client,
        ),
    }
    payloads["empty_dict"] = {
        "description": "Empty dictionary",
        "output": to_json({}, PROJECT_ID, client),
    }
    payloads["empty_list"] = {
        "description": "Empty list",
        "output": to_json([], PROJECT_ID, client),
    }
    payloads["list_of_dicts"] = {
        "description": "List of dictionaries",
        "output": to_json(
            [{"name": "a", "value": 1}, {"name": "b", "value": 2}],
            PROJECT_ID,
            client,
        ),
    }
    payloads["deeply_nested"] = {
        "description": "Deeply nested structure",
        "output": to_json(
            {"l1": {"l2": {"l3": {"l4": "deep"}}}},
            PROJECT_ID,
            client,
        ),
    }

    # ── Refs ────────────────────────────────────────────────────────────
    obj_ref = ObjectRef(
        entity="test-entity",
        project="test-project",
        name="my-model",
        _digest="abc123def456",
    )
    payloads["object_ref"] = {
        "description": "ObjectRef serializes to weave:/// URI string",
        "output": to_json(obj_ref, PROJECT_ID, client),
    }

    table_ref = TableRef(
        entity="test-entity",
        project="test-project",
        _digest="def456abc789",
    )
    payloads["table_ref"] = {
        "description": "TableRef serializes to weave:/// URI string",
        "output": to_json(table_ref, PROJECT_ID, client),
    }

    op_ref = OpRef(
        entity="test-entity",
        project="test-project",
        name="my-op",
        _digest="op123digest",
    )
    payloads["op_ref"] = {
        "description": "OpRef serializes to weave:/// URI string",
        "output": to_json(op_ref, PROJECT_ID, client),
    }

    # ── ObjectRecord ────────────────────────────────────────────────────
    simple_record = ObjectRecord(
        {
            "_class_name": "MyModel",
            "name": "test-model",
            "value": 42,
            "tags": ["a", "b"],
        }
    )
    payloads["object_record_simple"] = {
        "description": "Simple ObjectRecord with primitive fields",
        "output": to_json(simple_record, PROJECT_ID, client),
    }

    nested_record = ObjectRecord(
        {
            "_class_name": "Config",
            "nested": {"lr": 0.001, "epochs": 10},
            "ref_field": obj_ref,
        }
    )
    payloads["object_record_with_ref"] = {
        "description": "ObjectRecord containing a ref field",
        "output": to_json(nested_record, PROJECT_ID, client),
    }

    # ── Named Tuple ─────────────────────────────────────────────────────
    Point = namedtuple("Point", ["x", "y"])
    payloads["named_tuple"] = {
        "description": "Named tuple serializes to dict with field names as keys",
        "output": to_json(Point(10, 20), PROJECT_ID, client),
    }

    # ── Datetime (CustomWeaveType via registered serializer) ────────────
    # encode_custom_obj needs a global weave client to save load ops.
    dt = datetime.datetime(2024, 1, 15, 10, 30, 0)
    with _mock_weave_context(client):
        payloads["datetime"] = {
            "description": "datetime.datetime serializes as CustomWeaveType with ISO val",
            "output": to_json(dt, PROJECT_ID, client),
        }

    # ── Tuple (serialized as list) ──────────────────────────────────────
    payloads["tuple_as_list"] = {
        "description": "Python tuples serialize as JSON arrays",
        "output": to_json((1, "two", 3.0), PROJECT_ID, client),
    }

    # ── Realistic call inputs ───────────────────────────────────────────
    payloads["realistic_call_inputs"] = {
        "description": "Realistic LLM call inputs with mixed types",
        "output": to_json(
            {
                "prompt": "Hello, world!",
                "temperature": 0.7,
                "max_tokens": 100,
                "stop_sequences": ["\n", "END"],
                "metadata": {
                    "user_id": "user-123",
                    "session": {"id": "sess-456", "turn": 3},
                },
                "model_ref": obj_ref,
            },
            PROJECT_ID,
            client,
        ),
    }

    # ── Static format fixtures (types requiring optional deps) ──────────
    # These document the canonical CustomWeaveType envelope without running
    # to_json, since the underlying types need optional libraries (PIL, etc.)
    payloads["custom_type_image_format"] = {
        "description": "Canonical CustomWeaveType format for PIL images",
        "static": True,
        "output": {
            "_type": "CustomWeaveType",
            "weave_type": {"type": "PIL.Image.Image"},
            "files": {"image.png": "<sha256_digest>"},
        },
    }
    payloads["custom_type_audio_format"] = {
        "description": "Canonical CustomWeaveType format for audio",
        "static": True,
        "output": {
            "_type": "CustomWeaveType",
            "weave_type": {"type": "wave.Wave_read"},
            "files": {"audio.wav": "<sha256_digest>"},
        },
    }

    return payloads


def _payload_to_json(payload: dict) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def write_payloads() -> None:
    """Generate and write each payload as an individual JSON file."""
    payloads = generate_payloads()
    CANONICAL_DIR.mkdir(parents=True, exist_ok=True)

    # Remove stale files that are no longer generated
    existing = {p.stem for p in CANONICAL_DIR.glob("*.json")}
    for stale in existing - set(payloads.keys()):
        (CANONICAL_DIR / f"{stale}.json").unlink()
        print(f"  Removed stale: {stale}.json")

    for name, payload in sorted(payloads.items()):
        path = CANONICAL_DIR / f"{name}.json"
        path.write_text(_payload_to_json(payload))

    print(f"Wrote {len(payloads)} payloads to {CANONICAL_DIR}/")


def check_payloads() -> bool:
    """Verify checked-in payloads match current to_json output. Returns True if OK."""
    payloads = generate_payloads()
    ok = True

    existing = {p.stem for p in CANONICAL_DIR.glob("*.json")}
    expected = set(payloads.keys())

    # Check for missing files
    for missing in expected - existing:
        print(f"MISSING: {missing}.json", file=sys.stderr)
        ok = False

    # Check for stale files
    for stale in existing - expected:
        print(f"STALE: {stale}.json (no longer generated)", file=sys.stderr)
        ok = False

    # Check content of each expected payload
    for name, payload in sorted(payloads.items()):
        path = CANONICAL_DIR / f"{name}.json"
        if not path.exists():
            continue

        current_json = path.read_text()
        expected_json = _payload_to_json(payload)

        if current_json != expected_json:
            print(f"CHANGED: {name}.json", file=sys.stderr)
            diff = difflib.unified_diff(
                current_json.splitlines(keepends=True),
                expected_json.splitlines(keepends=True),
                fromfile=f"checked-in {name}.json",
                tofile=f"current {name}.json",
            )
            sys.stderr.writelines(diff)
            ok = False

    if ok:
        print(f"OK: {len(payloads)} payloads are up to date")
    else:
        print(
            "\nRun: python scripts/generate_serialization_fixtures.py",
            file=sys.stderr,
        )

    return ok


if __name__ == "__main__":
    if "--check" in sys.argv:
        sys.exit(0 if check_payloads() else 1)
    else:
        write_payloads()
