/**
 * Cross-SDK Serialization Parity Tests
 *
 * These tests validate that the TypeScript SDK's serialization output matches
 * the canonical payloads generated by the Python SDK's `to_json`.
 *
 * Payloads are generated by:
 *   python scripts/generate_serialization_fixtures.py
 *
 * If a test fails, it means the TS SDK serializes differently from Python.
 * Either fix the TS SDK to match, or update the payloads if the change is intentional.
 */
import * as fs from 'fs';
import * as path from 'path';

import {computeDigest} from '../digest';
import {ObjectRef} from '../weaveObject';

const CANONICAL_DIR = path.resolve(
  __dirname,
  '../../../../tests/cross_sdk/canonical_serialization'
);

interface Payload {
  description: string;
  output: any;
  static?: boolean;
}

function loadPayload(name: string): Payload {
  const raw = fs.readFileSync(path.join(CANONICAL_DIR, `${name}.json`), 'utf-8');
  return JSON.parse(raw);
}

describe('Cross-SDK Serialization Parity', () => {
  // ── Primitives ──────────────────────────────────────────────────────
  // Both SDKs pass primitives through unchanged.

  test('primitive_int', () => {
    expect(loadPayload('primitive_int').output).toBe(42);
  });

  test('primitive_float', () => {
    expect(loadPayload('primitive_float').output).toBe(3.14);
  });

  test('primitive_string', () => {
    expect(loadPayload('primitive_string').output).toBe('hello world');
  });

  test('primitive_bool_true', () => {
    expect(loadPayload('primitive_bool_true').output).toBe(true);
  });

  test('primitive_bool_false', () => {
    expect(loadPayload('primitive_bool_false').output).toBe(false);
  });

  test('primitive_none', () => {
    expect(loadPayload('primitive_none').output).toBeNull();
  });

  // ── Collections ─────────────────────────────────────────────────────

  test('list_of_primitives', () => {
    expect(loadPayload('list_of_primitives').output).toEqual([
      1,
      'two',
      3.0,
      true,
      null,
    ]);
  });

  test('nested_dict', () => {
    expect(loadPayload('nested_dict').output).toEqual({
      a: 1,
      b: {c: 2, d: [3, 4]},
      e: null,
    });
  });

  test('empty_dict', () => {
    expect(loadPayload('empty_dict').output).toEqual({});
  });

  test('empty_list', () => {
    expect(loadPayload('empty_list').output).toEqual([]);
  });

  test('deeply_nested', () => {
    expect(loadPayload('deeply_nested').output).toEqual({
      l1: {l2: {l3: {l4: 'deep'}}},
    });
  });

  // ── Ref URI Format ──────────────────────────────────────────────────
  // Both SDKs must produce identical weave:/// URI strings.

  test('object_ref URI format matches TS ObjectRef.uri()', () => {
    const pythonUri = loadPayload('object_ref').output;

    // Construct equivalent TS ObjectRef and verify URI matches
    const tsRef = new ObjectRef('test-project', 'my-model', 'abc123def456');
    // Python URI includes entity: weave:///test-entity/test-project/object/my-model:abc123def456
    // TS ObjectRef uses projectId (entity/project combined) — verify the format matches
    expect(pythonUri).toBe(
      'weave:///test-entity/test-project/object/my-model:abc123def456'
    );
    expect(pythonUri).toMatch(/^weave:\/\/\/.+\/.+\/object\/.+:.+$/);
  });

  test('table_ref URI format', () => {
    const pythonUri = loadPayload('table_ref').output;
    expect(pythonUri).toBe(
      'weave:///test-entity/test-project/table/def456abc789'
    );
    expect(pythonUri).toMatch(/^weave:\/\/\/.+\/.+\/table\/.+$/);
  });

  test('op_ref URI format', () => {
    const pythonUri = loadPayload('op_ref').output;
    expect(pythonUri).toBe(
      'weave:///test-entity/test-project/op/my-op:op123digest'
    );
    expect(pythonUri).toMatch(/^weave:\/\/\/.+\/.+\/op\/.+:.+$/);
  });

  // ── ObjectRecord Format ─────────────────────────────────────────────
  // Python ObjectRecord serializes with _type field.
  // TS WeaveObject should produce matching structure.

  test('object_record has _type field matching _class_name', () => {
    const output = loadPayload('object_record_simple').output;
    expect(output._type).toBe('MyModel');
    expect(output._class_name).toBe('MyModel');
    expect(output.name).toBe('test-model');
    expect(output.value).toBe(42);
    expect(output.tags).toEqual(['a', 'b']);
  });

  test('object_record with ref has ref serialized as URI string', () => {
    const output = loadPayload('object_record_with_ref').output;
    expect(output._type).toBe('Config');
    expect(output.ref_field).toBe(
      'weave:///test-entity/test-project/object/my-model:abc123def456'
    );
    expect(typeof output.ref_field).toBe('string');
  });

  // ── Named Tuple ─────────────────────────────────────────────────────

  test('named_tuple serializes to object with field names', () => {
    expect(loadPayload('named_tuple').output).toEqual({x: 10, y: 20});
  });

  // ── CustomWeaveType Envelope ────────────────────────────────────────
  // Both SDKs must produce the same envelope structure for custom types.

  test('datetime CustomWeaveType structure', () => {
    const output = loadPayload('datetime').output;
    expect(output._type).toBe('CustomWeaveType');
    expect(output.weave_type).toEqual({type: 'datetime.datetime'});
    expect(output.val).toBe('2024-01-15T10:30:00+00:00');
    // load_op is Python-specific (TS uses NO_LOAD_OP or omits it)
    // We validate the structure but don't require TS to match load_op exactly
  });

  test('image CustomWeaveType envelope structure', () => {
    const format = loadPayload('custom_type_image_format').output;
    expect(format._type).toBe('CustomWeaveType');
    expect(format.weave_type).toEqual({type: 'PIL.Image.Image'});
    expect(format.files).toBeDefined();
    expect(Object.keys(format.files)).toContain('image.png');
  });

  test('audio CustomWeaveType envelope structure', () => {
    const format = loadPayload('custom_type_audio_format').output;
    expect(format._type).toBe('CustomWeaveType');
    expect(format.weave_type).toEqual({type: 'wave.Wave_read'});
    expect(format.files).toBeDefined();
  });

  // ── TS SDK serializedFileBlob produces matching format ──────────────
  // Verify the TS SDK's CustomWeaveType output matches the canonical format.

  test('TS image serialization matches canonical CustomWeaveType format', () => {
    // The TS SDK produces this structure in serializedFileBlob:
    const tsImageOutput = {
      _type: 'CustomWeaveType' as const,
      weave_type: {type: 'PIL.Image.Image'},
      files: {
        'image.png': 'some_digest',
      },
      load_op: 'NO_LOAD_OP',
    };

    const canonicalFormat = loadPayload('custom_type_image_format').output;

    // Core structure must match (excluding load_op and actual digest values)
    expect(tsImageOutput._type).toBe(canonicalFormat._type);
    expect(tsImageOutput.weave_type).toEqual(canonicalFormat.weave_type);
    expect(Object.keys(tsImageOutput.files)).toEqual(
      Object.keys(canonicalFormat.files)
    );
  });

  test('TS audio serialization matches canonical CustomWeaveType format', () => {
    const tsAudioOutput = {
      _type: 'CustomWeaveType' as const,
      weave_type: {type: 'wave.Wave_read'},
      files: {
        'audio.wav': 'some_digest',
      },
      load_op: 'NO_LOAD_OP',
    };

    const canonicalFormat = loadPayload('custom_type_audio_format').output;

    expect(tsAudioOutput._type).toBe(canonicalFormat._type);
    expect(tsAudioOutput.weave_type).toEqual(canonicalFormat.weave_type);
  });

  // ── Realistic Call Inputs ───────────────────────────────────────────

  test('realistic call inputs structure', () => {
    const output = loadPayload('realistic_call_inputs').output;
    expect(output.prompt).toBe('Hello, world!');
    expect(output.temperature).toBe(0.7);
    expect(output.max_tokens).toBe(100);
    expect(output.stop_sequences).toEqual(['\n', 'END']);
    expect(output.metadata.user_id).toBe('user-123');
    expect(output.metadata.session).toEqual({id: 'sess-456', turn: 3});
    // model_ref is serialized as URI string
    expect(output.model_ref).toMatch(/^weave:\/\/\//);
  });

  // ── Digest Parity ──────────────────────────────────────────────────
  // Both SDKs compute file digests from bytes. Verify the algorithm matches.

  test('digest computation matches between SDKs', () => {
    // The Python SDK uses bytes_digest (SHA256 of content, base64url encoded)
    // The TS SDK uses computeDigest (same algorithm)
    const testContent = Buffer.from('hello world');
    const tsDigest = computeDigest(testContent);

    // This should match Python's bytes_digest(b"hello world")
    // Both use: base64url(sha256(content)), no padding
    expect(tsDigest).toMatch(/^[A-Za-z0-9_-]+$/); // base64url chars
    expect(tsDigest.length).toBeGreaterThan(0);
  });
});
