"""Compatibility exports for weave.shared.builtin_object_classes.agent_dashboard."""

from weave.shared.builtin_object_classes.agent_dashboard import (
    DASHBOARD_GRID_COLUMNS,
    AgentDashboard,
    AgentDashboardDefinition,
    BaseModel,
    BreakdownDashboardPanel,
    BreakdownPanelQueryConfig,
    BreakdownPanelSettings,
    ConfigDict,
    DashboardConfigModel,
    DashboardPanel,
    DashboardPanelBase,
    Field,
    KpiDashboardPanel,
    KpiPanelQueryConfig,
    KpiPanelSettings,
    Literal,
    PanelGridLayout,
    PanelQueryConfig,
    PanelValueFormat,
    TimelineDashboardPanel,
    TimelinePanelQueryConfig,
    TimelinePanelSettings,
    base_object_def,
    model_validator,
)

__all__ = [
    "DASHBOARD_GRID_COLUMNS",
    "AgentDashboard",
    "AgentDashboardDefinition",
    "BaseModel",
    "BreakdownDashboardPanel",
    "BreakdownPanelQueryConfig",
    "BreakdownPanelSettings",
    "ConfigDict",
    "DashboardConfigModel",
    "DashboardPanel",
    "DashboardPanelBase",
    "Field",
    "KpiDashboardPanel",
    "KpiPanelQueryConfig",
    "KpiPanelSettings",
    "Literal",
    "PanelGridLayout",
    "PanelQueryConfig",
    "PanelValueFormat",
    "TimelineDashboardPanel",
    "TimelinePanelQueryConfig",
    "TimelinePanelSettings",
    "base_object_def",
    "model_validator",
]
