import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  documentationSidebar: [
    {
      type: "category",
      collapsible: true,
      collapsed: false,
      label: "Getting Started",
      items: [
        "introduction",
        "quickstart",
        "tutorial-tracing_2",
        "tutorial-weave_models",
        "tutorial-eval",
        "tutorial-rag",
      ],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: false,
      label: "Using Weave",
      items: [
        {
          type: "category",
          collapsible: true,
          collapsed: false,
          label: "Core Types",
          link: { type: "doc", id: "guides/core-types/index" },
          items: [
            "guides/core-types/models",
            "guides/core-types/datasets",
            "guides/core-types/evaluations",
          ],
        },
        {
          type: "category",
          collapsible: true,
          collapsed: false,
          label: "Tracking",
          link: { type: "doc", id: "guides/tracking/index" },
          items: [
            "guides/tracking/objects",
            "guides/tracking/ops",
            "guides/tracking/tracing",
            "guides/tracking/feedback",
          ],
        },
        {
          type: "category",
          collapsible: true,
          collapsed: true,
          label: "Integrations",
          link: { type: "doc", id: "guides/integrations/index" },
          items: [
            "guides/integrations/openai",
            "guides/integrations/anthropic",
            "guides/integrations/cohere",
            "guides/integrations/mistral",
            "guides/integrations/langchain",
            "guides/integrations/llamaindex",
            "guides/integrations/dspy",
            "guides/integrations/google-gemini",
            "guides/integrations/together_ai",
            "guides/integrations/groq",
            "guides/integrations/openrouter",
            "guides/integrations/local_models",
            "guides/integrations/litellm",
          ],
        },
        {
          type: 'html',
          value: '<div class="sidebar-section-title">Section Title<div>', // The HTML to be rendered
          defaultStyle: true, // Use the default menu item styling
        },
        {
          type: "category",
          collapsible: true,
          collapsed: true,
          label: "Tools",
          link: { type: "doc", id: "guides/tools/index" },
          items: ["guides/tools/serve", "guides/tools/deploy"],
        },
        {
          type: "doc",
          id: "guides/platform/index",
        },
      ],
    },
  ],
  pythonSdkSidebar: [{ type: "autogenerated", dirName: "reference/python-sdk" }],
  serviceApiSidebar: require("./docs/reference/service-api/sidebar.ts").filter((row) => {
    if (row.id == "reference/service-api/fastapi") {
      // Remove FastAPI from the sidebar - this is a default homepage that is not useful for us
      return false;
    }

    // Hide the `Service` category from the sidebar
    if (row.label == "Service") {
      return false;
    }

    return true;
  }),
};

export default sidebars;
