import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  documentationSidebar: [
    {
      type: "category",
      collapsible: true,
      collapsed: false,
      label: "Getting Started",
      items: [
        "introduction",
        "quickstart",
        "tutorial-tracing_2",
        "tutorial-weave_models",
        "tutorial-eval",
        "tutorial-rag",
      ],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: false,
      label: "Using Weave",
      items: [
        {
          type: "category",
          collapsible: true,
          collapsed: false,
          label: "Core Types",
          link: { type: "doc", id: "guides/core-types/index" },
          items: [
            "guides/core-types/models",
            "guides/core-types/datasets",
            "guides/core-types/evaluations",
          ],
        },
        {
          type: "category",
          collapsible: true,
          collapsed: false,
          label: "Tracking",
          link: { type: "doc", id: "guides/tracking/index" },
          items: [
            "guides/tracking/objects",
            "guides/tracking/ops",
            "guides/tracking/tracing",
            "guides/tracking/feedback",
          ],
        },
        {
          type: "category",
          collapsible: true,
          collapsed: true,
          label: "Integrations",
          link: { type: "doc", id: "guides/integrations/index" },
          items: [
            "guides/integrations/openai",
            "guides/integrations/anthropic",
            "guides/integrations/cohere",
            "guides/integrations/mistral",
            "guides/integrations/langchain",
            "guides/integrations/llamaindex",
            "guides/integrations/dspy",
            "guides/integrations/google-gemini",
            "guides/integrations/together_ai",
            "guides/integrations/groq",
            "guides/integrations/openrouter",
            "guides/integrations/local_models",
            "guides/integrations/litellm",
          ],
        },
        {
          type: "category",
          collapsible: true,
          collapsed: true,
          label: "Tools",
          link: { type: "doc", id: "guides/tools/index" },
          items: ["guides/tools/serve", "guides/tools/deploy"],
        },
        {
          type: "doc",
          id: "guides/platform/index",
        },
      ],
    },
  ],
  pythonSdkSidebar: [{ type: "autogenerated", dirName: "reference/python-sdk" }],
  serviceApiSidebar: [{type: "autogenerated", dirName: "reference/service-api"}],
};

export default sidebars;
