update_costs:
	python trace_server/costs/update_costs.py

generate_base_object_schemas:
	python scripts/generate_base_object_schemas.py

update_model_providers:
	python trace_server/model_providers/model_providers.py
