from dataclasses import dataclass
from typing import Annotated, Any, ClassVar, Literal

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field, model_validator

from weave.shared import refs_internal
from weave.shared.trace_server.interface.builtin_object_classes import base_object_def

ResponseFormat = Literal["json_object", "json_schema", "text"]


def is_response_format(value: Any) -> bool:
    return isinstance(value, str) and value in {"json_object", "text"}


class Message(BaseModel):
    """A message in a conversation with an LLM.

    Attributes:
        role: The role of the message's author. Can be: system, user, assistant, function or tool.
        content: The contents of the message. Required for all messages, but may be null for assistant messages with function calls.
        name: The name of the author of the message. Required if role is "function". Must match the name of the function represented in content.
              Can contain characters (a-z, A-Z, 0-9), and underscores, with a maximum length of 64 characters.
        function_call: The name and arguments of a function that should be called, as generated by the model.
        tool_call_id: Tool call that this message is responding to.
    """

    role: str
    content: str | list[dict] | None = None
    name: str | None = None
    function_call: dict | None = None
    tool_call_id: str | None = None


class LLMStructuredCompletionModelDefaultParams(BaseModel):
    """Default parameters for LLMStructuredCompletionModel.

    Attributes:
        messages_template: A list of Messages to use as a template. Messages can contain
            template variables using {variable_name} syntax. These will be substituted
            when predict() is called with template_vars.
        prompt: A reference string to a MessagesPrompt object. If provided, this takes
            precedence over messages_template. The referenced prompt's format() method will
            be used to generate messages with template variable substitution.
            Example: "weave:///entity/project/object/my_prompt:latest"
    """

    # This is a list of Messages, loosely following litellm's message format
    # https://docs.litellm.ai/docs/completion/input#properties-of-messages
    messages_template: list[Message] | None = None
    prompt: base_object_def.RefStr | None = None

    temperature: float | None = None
    top_p: float | None = None
    max_tokens: int | None = None
    presence_penalty: float | None = None
    frequency_penalty: float | None = None
    stop: list[str] | None = None
    n_times: int | None = None
    functions: list[dict] | None = None

    # Either json, text, or json_schema
    response_format: ResponseFormat | None = None


def cast_to_message_list(obj: Any) -> list[Message]:
    if isinstance(obj, Message):
        return [obj]
    elif isinstance(obj, dict):
        return [Message.model_validate(obj)]
    elif isinstance(obj, str):
        return [Message(content=obj, role="user")]
    elif isinstance(obj, list):
        return [cast_to_message(item) for item in obj]
    raise TypeError("Unable to cast to Message")


def cast_to_message(obj: Any) -> Message:
    if isinstance(obj, Message):
        return obj
    elif isinstance(obj, dict):
        return Message.model_validate(obj)
    elif isinstance(obj, str):
        return Message(content=obj, role="user")
    raise TypeError("Unable to cast to Message")


def cast_to_llm_structured_model_params(
    obj: Any,
) -> LLMStructuredCompletionModelDefaultParams:
    if isinstance(obj, LLMStructuredCompletionModelDefaultParams):
        return obj
    if isinstance(obj, dict):
        return LLMStructuredCompletionModelDefaultParams.model_validate(obj)
    raise TypeError("Unable to cast to LLMStructuredCompletionModelDefaultParams")


MessageListLike = Annotated[list[Message], BeforeValidator(cast_to_message_list)]
MessageLike = Annotated[Message, BeforeValidator(cast_to_message)]
LLMStructuredModelParamsLike = Annotated[
    LLMStructuredCompletionModelDefaultParams,
    BeforeValidator(cast_to_llm_structured_model_params),
]


@dataclass(frozen=True)
class ObjectRef:
    entity: str
    project: str
    name: str
    _digest: str
    _extra: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        refs_internal.validate_no_slashes(self._digest, "digest")
        refs_internal.validate_no_colons(self._digest, "digest")
        refs_internal.validate_no_slashes(self.name, "name")
        refs_internal.validate_no_colons(self.name, "name")


class LLMStructuredCompletionModel(base_object_def.BaseObject):
    # Stored object identity predates the schema/SDK implementation split.
    __weave_serialized_bases__: ClassVar[tuple[str, ...]] = (
        "Model",
        "Object",
        "BaseModel",
    )
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    ref: ObjectRef | None = Field(default=None, repr=False)
    llm_model_id: str | base_object_def.RefStr
    default_params: LLMStructuredModelParamsLike = Field(
        default_factory=LLMStructuredCompletionModelDefaultParams
    )

    @model_validator(mode="before")
    @classmethod
    def strip_weave_serialization_metadata(cls, data: Any) -> Any:
        if isinstance(data, dict):
            return {
                k: v
                for k, v in data.items()
                if k not in {"_type", "_class_name", "_bases"}
            }
        return data
