/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { blobLikeSchema } from "../../types/blobs.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FileT = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BodyFileCreateFileCreatePost = {
  file: FileT | Blob;
  projectId: string;
};

/** @internal */
export const FileT$inboundSchema: z.ZodType<FileT, z.ZodTypeDef, unknown> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.instanceof(ReadableStream<Uint8Array>),
      z.instanceof(Blob),
      z.instanceof(ArrayBuffer),
      z.instanceof(Uint8Array),
    ]),
  });

/** @internal */
export type FileT$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const FileT$outboundSchema: z.ZodType<
  FileT$Outbound,
  z.ZodTypeDef,
  FileT
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileT$ {
  /** @deprecated use `FileT$inboundSchema` instead. */
  export const inboundSchema = FileT$inboundSchema;
  /** @deprecated use `FileT$outboundSchema` instead. */
  export const outboundSchema = FileT$outboundSchema;
  /** @deprecated use `FileT$Outbound` instead. */
  export type Outbound = FileT$Outbound;
}

export function fileToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

export function fileFromJSON(
  jsonString: string,
): SafeParseResult<FileT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileT' from JSON`,
  );
}

/** @internal */
export const BodyFileCreateFileCreatePost$inboundSchema: z.ZodType<
  BodyFileCreateFileCreatePost,
  z.ZodTypeDef,
  unknown
> = z.object({
  file: z.lazy(() => FileT$inboundSchema),
  project_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "project_id": "projectId",
  });
});

/** @internal */
export type BodyFileCreateFileCreatePost$Outbound = {
  file: FileT$Outbound | Blob;
  project_id: string;
};

/** @internal */
export const BodyFileCreateFileCreatePost$outboundSchema: z.ZodType<
  BodyFileCreateFileCreatePost$Outbound,
  z.ZodTypeDef,
  BodyFileCreateFileCreatePost
> = z.object({
  file: z.lazy(() => FileT$outboundSchema).or(blobLikeSchema),
  projectId: z.string(),
}).transform((v) => {
  return remap$(v, {
    projectId: "project_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BodyFileCreateFileCreatePost$ {
  /** @deprecated use `BodyFileCreateFileCreatePost$inboundSchema` instead. */
  export const inboundSchema = BodyFileCreateFileCreatePost$inboundSchema;
  /** @deprecated use `BodyFileCreateFileCreatePost$outboundSchema` instead. */
  export const outboundSchema = BodyFileCreateFileCreatePost$outboundSchema;
  /** @deprecated use `BodyFileCreateFileCreatePost$Outbound` instead. */
  export type Outbound = BodyFileCreateFileCreatePost$Outbound;
}

export function bodyFileCreateFileCreatePostToJSON(
  bodyFileCreateFileCreatePost: BodyFileCreateFileCreatePost,
): string {
  return JSON.stringify(
    BodyFileCreateFileCreatePost$outboundSchema.parse(
      bodyFileCreateFileCreatePost,
    ),
  );
}

export function bodyFileCreateFileCreatePostFromJSON(
  jsonString: string,
): SafeParseResult<BodyFileCreateFileCreatePost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BodyFileCreateFileCreatePost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BodyFileCreateFileCreatePost' from JSON`,
  );
}
