/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CallsDeleteRes = {};

/** @internal */
export const CallsDeleteRes$inboundSchema: z.ZodType<
  CallsDeleteRes,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type CallsDeleteRes$Outbound = {};

/** @internal */
export const CallsDeleteRes$outboundSchema: z.ZodType<
  CallsDeleteRes$Outbound,
  z.ZodTypeDef,
  CallsDeleteRes
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CallsDeleteRes$ {
  /** @deprecated use `CallsDeleteRes$inboundSchema` instead. */
  export const inboundSchema = CallsDeleteRes$inboundSchema;
  /** @deprecated use `CallsDeleteRes$outboundSchema` instead. */
  export const outboundSchema = CallsDeleteRes$outboundSchema;
  /** @deprecated use `CallsDeleteRes$Outbound` instead. */
  export type Outbound = CallsDeleteRes$Outbound;
}

export function callsDeleteResToJSON(callsDeleteRes: CallsDeleteRes): string {
  return JSON.stringify(CallsDeleteRes$outboundSchema.parse(callsDeleteRes));
}

export function callsDeleteResFromJSON(
  jsonString: string,
): SafeParseResult<CallsDeleteRes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CallsDeleteRes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CallsDeleteRes' from JSON`,
  );
}
