/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CostPurgeRes = {};

/** @internal */
export const CostPurgeRes$inboundSchema: z.ZodType<
  CostPurgeRes,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type CostPurgeRes$Outbound = {};

/** @internal */
export const CostPurgeRes$outboundSchema: z.ZodType<
  CostPurgeRes$Outbound,
  z.ZodTypeDef,
  CostPurgeRes
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CostPurgeRes$ {
  /** @deprecated use `CostPurgeRes$inboundSchema` instead. */
  export const inboundSchema = CostPurgeRes$inboundSchema;
  /** @deprecated use `CostPurgeRes$outboundSchema` instead. */
  export const outboundSchema = CostPurgeRes$outboundSchema;
  /** @deprecated use `CostPurgeRes$Outbound` instead. */
  export type Outbound = CostPurgeRes$Outbound;
}

export function costPurgeResToJSON(costPurgeRes: CostPurgeRes): string {
  return JSON.stringify(CostPurgeRes$outboundSchema.parse(costPurgeRes));
}

export function costPurgeResFromJSON(
  jsonString: string,
): SafeParseResult<CostPurgeRes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CostPurgeRes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CostPurgeRes' from JSON`,
  );
}
