/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FeedbackPurgeRes = {};

/** @internal */
export const FeedbackPurgeRes$inboundSchema: z.ZodType<
  FeedbackPurgeRes,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type FeedbackPurgeRes$Outbound = {};

/** @internal */
export const FeedbackPurgeRes$outboundSchema: z.ZodType<
  FeedbackPurgeRes$Outbound,
  z.ZodTypeDef,
  FeedbackPurgeRes
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FeedbackPurgeRes$ {
  /** @deprecated use `FeedbackPurgeRes$inboundSchema` instead. */
  export const inboundSchema = FeedbackPurgeRes$inboundSchema;
  /** @deprecated use `FeedbackPurgeRes$outboundSchema` instead. */
  export const outboundSchema = FeedbackPurgeRes$outboundSchema;
  /** @deprecated use `FeedbackPurgeRes$Outbound` instead. */
  export type Outbound = FeedbackPurgeRes$Outbound;
}

export function feedbackPurgeResToJSON(
  feedbackPurgeRes: FeedbackPurgeRes,
): string {
  return JSON.stringify(
    FeedbackPurgeRes$outboundSchema.parse(feedbackPurgeRes),
  );
}

export function feedbackPurgeResFromJSON(
  jsonString: string,
): SafeParseResult<FeedbackPurgeRes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeedbackPurgeRes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeedbackPurgeRes' from JSON`,
  );
}
