/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FileContentReadReq = {
  projectId: string;
  digest: string;
};

/** @internal */
export const FileContentReadReq$inboundSchema: z.ZodType<
  FileContentReadReq,
  z.ZodTypeDef,
  unknown
> = z.object({
  project_id: z.string(),
  digest: z.string(),
}).transform((v) => {
  return remap$(v, {
    "project_id": "projectId",
  });
});

/** @internal */
export type FileContentReadReq$Outbound = {
  project_id: string;
  digest: string;
};

/** @internal */
export const FileContentReadReq$outboundSchema: z.ZodType<
  FileContentReadReq$Outbound,
  z.ZodTypeDef,
  FileContentReadReq
> = z.object({
  projectId: z.string(),
  digest: z.string(),
}).transform((v) => {
  return remap$(v, {
    projectId: "project_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileContentReadReq$ {
  /** @deprecated use `FileContentReadReq$inboundSchema` instead. */
  export const inboundSchema = FileContentReadReq$inboundSchema;
  /** @deprecated use `FileContentReadReq$outboundSchema` instead. */
  export const outboundSchema = FileContentReadReq$outboundSchema;
  /** @deprecated use `FileContentReadReq$Outbound` instead. */
  export type Outbound = FileContentReadReq$Outbound;
}

export function fileContentReadReqToJSON(
  fileContentReadReq: FileContentReadReq,
): string {
  return JSON.stringify(
    FileContentReadReq$outboundSchema.parse(fileContentReadReq),
  );
}

export function fileContentReadReqFromJSON(
  jsonString: string,
): SafeParseResult<FileContentReadReq, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileContentReadReq$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileContentReadReq' from JSON`,
  );
}
