/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FileCreateRes = {
  digest: string;
};

/** @internal */
export const FileCreateRes$inboundSchema: z.ZodType<
  FileCreateRes,
  z.ZodTypeDef,
  unknown
> = z.object({
  digest: z.string(),
});

/** @internal */
export type FileCreateRes$Outbound = {
  digest: string;
};

/** @internal */
export const FileCreateRes$outboundSchema: z.ZodType<
  FileCreateRes$Outbound,
  z.ZodTypeDef,
  FileCreateRes
> = z.object({
  digest: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileCreateRes$ {
  /** @deprecated use `FileCreateRes$inboundSchema` instead. */
  export const inboundSchema = FileCreateRes$inboundSchema;
  /** @deprecated use `FileCreateRes$outboundSchema` instead. */
  export const outboundSchema = FileCreateRes$outboundSchema;
  /** @deprecated use `FileCreateRes$Outbound` instead. */
  export type Outbound = FileCreateRes$Outbound;
}

export function fileCreateResToJSON(fileCreateRes: FileCreateRes): string {
  return JSON.stringify(FileCreateRes$outboundSchema.parse(fileCreateRes));
}

export function fileCreateResFromJSON(
  jsonString: string,
): SafeParseResult<FileCreateRes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileCreateRes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileCreateRes' from JSON`,
  );
}
