/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ObjCreateRes = {
  digest: string;
};

/** @internal */
export const ObjCreateRes$inboundSchema: z.ZodType<
  ObjCreateRes,
  z.ZodTypeDef,
  unknown
> = z.object({
  digest: z.string(),
});

/** @internal */
export type ObjCreateRes$Outbound = {
  digest: string;
};

/** @internal */
export const ObjCreateRes$outboundSchema: z.ZodType<
  ObjCreateRes$Outbound,
  z.ZodTypeDef,
  ObjCreateRes
> = z.object({
  digest: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ObjCreateRes$ {
  /** @deprecated use `ObjCreateRes$inboundSchema` instead. */
  export const inboundSchema = ObjCreateRes$inboundSchema;
  /** @deprecated use `ObjCreateRes$outboundSchema` instead. */
  export const outboundSchema = ObjCreateRes$outboundSchema;
  /** @deprecated use `ObjCreateRes$Outbound` instead. */
  export type Outbound = ObjCreateRes$Outbound;
}

export function objCreateResToJSON(objCreateRes: ObjCreateRes): string {
  return JSON.stringify(ObjCreateRes$outboundSchema.parse(objCreateRes));
}

export function objCreateResFromJSON(
  jsonString: string,
): SafeParseResult<ObjCreateRes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ObjCreateRes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ObjCreateRes' from JSON`,
  );
}
