/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ObjReadReq = {
  projectId: string;
  objectId: string;
  digest: string;
};

/** @internal */
export const ObjReadReq$inboundSchema: z.ZodType<
  ObjReadReq,
  z.ZodTypeDef,
  unknown
> = z.object({
  project_id: z.string(),
  object_id: z.string(),
  digest: z.string(),
}).transform((v) => {
  return remap$(v, {
    "project_id": "projectId",
    "object_id": "objectId",
  });
});

/** @internal */
export type ObjReadReq$Outbound = {
  project_id: string;
  object_id: string;
  digest: string;
};

/** @internal */
export const ObjReadReq$outboundSchema: z.ZodType<
  ObjReadReq$Outbound,
  z.ZodTypeDef,
  ObjReadReq
> = z.object({
  projectId: z.string(),
  objectId: z.string(),
  digest: z.string(),
}).transform((v) => {
  return remap$(v, {
    projectId: "project_id",
    objectId: "object_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ObjReadReq$ {
  /** @deprecated use `ObjReadReq$inboundSchema` instead. */
  export const inboundSchema = ObjReadReq$inboundSchema;
  /** @deprecated use `ObjReadReq$outboundSchema` instead. */
  export const outboundSchema = ObjReadReq$outboundSchema;
  /** @deprecated use `ObjReadReq$Outbound` instead. */
  export type Outbound = ObjReadReq$Outbound;
}

export function objReadReqToJSON(objReadReq: ObjReadReq): string {
  return JSON.stringify(ObjReadReq$outboundSchema.parse(objReadReq));
}

export function objReadReqFromJSON(
  jsonString: string,
): SafeParseResult<ObjReadReq, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ObjReadReq$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ObjReadReq' from JSON`,
  );
}
