# When we push commits, fire off a `weave-package-updated`
# repository dispatch event to wandb/core

name: Notify wandb/core of branch push
run-name: Notify wandb/core - push to ${{ github.event.ref }}

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  check-which-tests-to-run:
    uses: ./.github/workflows/check-which-tests-to-run.yaml

  notify-wandb-core:
    needs: [check-which-tests-to-run]
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ vars.WANDBOT_3000_APP_ID }}
          private-key: ${{ secrets.WANDBOT_3000_PRIVATE_KEY }}
          owner: wandb
          repositories: core
          permission-contents: write

      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: wandb/core
          event-type: weave-package-updated
          client-payload: |-
            {
              "ref_name": "${{ github.ref_name }}",
              "sha": "${{ github.sha }}",
              "run_trace_server_tests": ${{ needs.check-which-tests-to-run.outputs.trace_server_tests }},
              "actor": "${{ github.actor }}",
              "actor_id": "${{ github.actor_id }}"
            }
