name: Validate PR

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  cc:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.PR_TITLE_GITHUB_TOKEN }}
        with:
          # Allowed types: https://www.notion.so/wandbai/Pull-Requests-17966b997841407b95b7c36414ae0634
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            analytics
            build
            ci
            chore
            revert
            security
            release
          wip: false
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: false
