name: publish-pypi-release

on:
  workflow_dispatch:
    inputs:
      is_test:
        description: "Use Test Pypi"
        required: true
        type: boolean
        default: true

jobs:
  build-release:
    name: Build and publish to pypi
    runs-on: ubuntu-8core
    timeout-minutes: 10
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
      - name: Install uv
        run: |
          pip install uv
      - name: Build dist
        run: |
          uv build
      - name: upload test distribution
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # release/v1
        if: ${{ inputs.is_test }}
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
      - name: upload distribution
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # release/v1
        if: ${{ !inputs.is_test }}

  # this job exists so that there's some traceability between weave SDk releases
  # and potential build failures in core.
  notify-core:
    name: notify wandb/core of release
    runs-on: ubuntu-latest
    if: "!inputs.is_test"
    needs: [build-release]

    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ vars.WANDBOT_3000_APP_ID }}
          private-key: ${{ secrets.WANDBOT_3000_PRIVATE_KEY }}
          owner: wandb
          repositories: core
          permission-contents: write

      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: wandb/core
          event-type: weave-sdk-released
          client-payload: |-
            {
              "ref_name": "${{ github.ref_name }}",
              "actor": "${{ github.actor }}",
              "actor_id": "${{ github.actor_id }}"
            }
