name: Rebuild frontend after wandb/core update

on:
  repository_dispatch:
    types:
      - core-updated
  workflow_dispatch:

jobs:
  update-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout weave
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 1
      - name: Checkout wandb/core
        uses: actions/checkout@v3
        with:
          path: .wandb_core
          submodules: false
          fetch-depth: 1
          repository: wandb/core
          ref: refs/heads/master
          token: ${{ secrets.WANDB_CORE_PAT }}
      - name: Placeholder
        run: git status
    # - name: Create working branch
    #   run: git checkout -b bot/update-frontend
    # - name: Rebuild frontend
    #   run: weave_query/scripts/build_frontend.sh
    #   env:
    #     WANDB_CORE: ${{ env.GITHUB_WORKSPACE }}/.wandb_core
