name: Rebuild frontend after wandb/core update

on:
  repository_dispatch:
    types:
      - core-updated
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout weave
        uses: actions/checkout@v6
        with:
          ref: master
          fetch-depth: 1
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.WANDBOT_3000_APP_ID }}
          private-key: ${{ secrets.WANDBOT_3000_PRIVATE_KEY }}
          owner: wandb
          repositories: core
          permission-contents: read
      - name: Checkout wandb/core
        uses: actions/checkout@v6
        with:
          path: .wandb_core
          submodules: false
          fetch-depth: 1
          repository: wandb/core
          ref: refs/heads/master
          token: ${{ steps.app-token.outputs.token }}
      - name: Placeholder
        run: git status
