name: Windows Container Smoke Test

# This workflow validates that Weave functions correctly on Windows
# by running smoke tests inside a Windows Server Core container

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  windows-container-test:
    runs-on: windows-2022
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Windows container
      run: |
        docker build -f tests/smoke/windows/Dockerfile.windows -t weave-windows-test:latest .
      
    - name: Run smoke tests in container
      run: |
        docker run --rm weave-windows-test:latest 